# Generated by Django 4.2.26 on 2025-12-12 18:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplateConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(choices=[('classic', 'Classic'), ('compact', 'Compact')], default='classic', help_text='Selected print template style (e.g. classic or compact).', max_length=20)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON of toggle states for various print options.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='print_template_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Template Configuration',
                'verbose_name_plural': 'Print Template Configurations',
                'permissions': [('can_edit_print_templates', 'Can edit print template settings')],
            },
        ),
    ]
