# Generated by GitHub Copilot on 2025-12-13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintSettingsAuditLog",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("organization_id", models.BigIntegerField(blank=True, null=True)),
                ("action", models.CharField(default="settings_update", max_length=64)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("user", models.ForeignKey(on_delete=models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="printsettingsauditlog",
            index=models.Index(fields=["user", "created_at"], name="printing_pr_user_id_7f1dfe_idx"),
        ),
        migrations.AddIndex(
            model_name="printsettingsauditlog",
            index=models.Index(fields=["organization_id", "created_at"], name="printing_pr_organiz_4b0c03_idx"),
        ),
    ]
