# Generated by GitHub Copilot on 2025-12-13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0002_printsettingsauditlog"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="printsettingsauditlog",
            old_name="printing_pr_user_id_7f1dfe_idx",
            new_name="printing_audit_user_ts_idx",
        ),
        migrations.RenameIndex(
            model_name="printsettingsauditlog",
            old_name="printing_pr_organiz_4b0c03_idx",
            new_name="printing_audit_org_ts_idx",
        ),
    ]
