# Generated by Django 5.0.14 on 2025-12-13 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0003_stable_audit_index_names'),
        ('usermanagement', '0030_add_auditlog_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('journal', 'Journal'), ('sales_order', 'Sales Order'), ('sales_quote', 'Sales Quote')], max_length=50)),
                ('name', models.CharField(help_text='User-defined name for this template.', max_length=100)),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A5', 'A5')], default='A4', max_length=10)),
                ('config', models.JSONField(blank=True, default=dict, help_text='JSON of template settings including toggles and template_name.')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Print Template',
                'verbose_name_plural': 'Print Templates',
                'unique_together': {('user', 'organization', 'document_type', 'name')},
            },
        ),
    ]
