# Generated by Django 5.0.14 on 2025-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printing', '0004_printtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='printtemplate',
            name='document_type',
            field=models.CharField(choices=[('journal', 'Journal'), ('purchase_order', 'Purchase Order'), ('sales_order', 'Sales Order'), ('sales_invoice', 'Sales Invoice')], max_length=50),
        ),
    ]
