# Generated by Django 5.0.14 on 2025-12-08 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_seed_journal_report'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='reportexecutionlog',
            new_name='reporting_r_organiz_8536c9_idx',
            old_name='reporting_r_organizat_7d61d8_idx',
        ),
        migrations.RenameIndex(
            model_name='reportexecutionlog',
            new_name='reporting_r_status_ab61c3_idx',
            old_name='reporting_r_status__698d25_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='reporting_s_organiz_4d22e1_idx',
            old_name='reporting_s_organiz_236bb4_idx',
        ),
        migrations.RenameIndex(
            model_name='scheduledreport',
            new_name='reporting_s_is_acti_75d462_idx',
            old_name='reporting_s_is_act_604c4d_idx',
        ),
    ]
