# Generated by Django 5.0.14 on 2025-12-08 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0003_rename_reporting_r_organizat_7d61d8_idx_reporting_r_organiz_8536c9_idx_and_more'),
        ('reporting', '0003_seed_core_reports'),
    ]

    operations = [
    ]
