# Generated by Django 4.2.26 on 2025-12-23 19:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesInvoiceDraft',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_prefix', models.CharField(default='SB', max_length=10)),
                ('invoice_no', models.PositiveIntegerField(blank=True, null=True)),
                ('invoice_series_id', models.PositiveIntegerField(blank=True, null=True)),
                ('fiscal_year', models.CharField(blank=True, max_length=20, null=True)),
                ('ref_no', models.CharField(blank=True, max_length=100, null=True)),
                ('date_bs', models.CharField(blank=True, max_length=20, null=True)),
                ('date_ad', models.DateField(blank=True, null=True)),
                ('due_days', models.PositiveIntegerField(default=30)),
                ('due_date_ad', models.DateField(blank=True, null=True)),
                ('buyer_id', models.PositiveIntegerField(blank=True, null=True)),
                ('buyer_snapshot', models.JSONField(blank=True, null=True)),
                ('sales_account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_mode', models.CharField(default='Credit', max_length=20)),
                ('order_ref_id', models.CharField(blank=True, max_length=100, null=True)),
                ('agent_id', models.PositiveIntegerField(blank=True, null=True)),
                ('agent_area_id', models.PositiveIntegerField(blank=True, null=True)),
                ('terms_id', models.PositiveIntegerField(blank=True, null=True)),
                ('narration', models.TextField(blank=True, null=True)),
                ('header_discount_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('header_discount_type', models.CharField(default='amt', max_length=4)),
                ('rounding_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nonvat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('nonvat_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_nonvat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vatable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vatable_discount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('total_vatable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('amount_in_words', models.CharField(default='Zero rupees only.', max_length=512)),
                ('remaining_balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sales Invoice Draft',
                'verbose_name_plural': 'Sales Invoice Drafts',
                'db_table': 'sales_invoice_draft',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceDraftReceipt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('account_id', models.PositiveIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('note', models.CharField(blank=True, max_length=256, null=True)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='vouchers.salesinvoicedraft')),
            ],
            options={
                'verbose_name': 'Sales Invoice Draft Receipt',
                'verbose_name_plural': 'Sales Invoice Draft Receipts',
                'db_table': 'sales_invoice_draft_receipt',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceDraftLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sn', models.PositiveIntegerField(default=1)),
                ('item_id', models.PositiveIntegerField(blank=True, null=True)),
                ('hs_code', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=256, null=True)),
                ('qty', models.DecimalField(decimal_places=2, default=1, max_digits=14)),
                ('unit_id', models.CharField(default='Nos', max_length=32)),
                ('godown_id', models.PositiveIntegerField(blank=True, null=True)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('disc_type', models.CharField(default='none', max_length=4)),
                ('disc_value', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('vat_applicable', models.BooleanField(default=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=13, max_digits=5)),
                ('net_rate', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_taxable', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('line_vat', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('draft', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='vouchers.salesinvoicedraft')),
            ],
            options={
                'verbose_name': 'Sales Invoice Draft Line',
                'verbose_name_plural': 'Sales Invoice Draft Lines',
                'db_table': 'sales_invoice_draft_line',
                'ordering': ['sn', 'id'],
            },
        ),
    ]
