# Generated by Django 4.2.26 on 2025-12-02 15:10

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0023_organization_address_organization_fiscal_year_start_and_more'),
        ('accounting', '0157_rename_accounting_salesinvoice_org_ird_status_idx_sales_invoi_organiz_fd59ef_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_categories', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceLifecycle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=150, unique=True)),
                ('asset_tag', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(choices=[('inventory', 'In Inventory'), ('provisioning', 'Provisioning'), ('deployed', 'Deployed/Active'), ('maintenance', 'Under Maintenance'), ('rma', 'RMA'), ('repair', 'In Repair'), ('retired', 'Retired'), ('disposed', 'Disposed')], default='inventory', max_length=20)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('customer_id', models.IntegerField(blank=True, null=True)),
                ('deployed_date', models.DateField(blank=True, null=True)),
                ('deployment_location', models.CharField(blank=True, max_length=200)),
                ('warranty_start_date', models.DateField(blank=True, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('extended_warranty', models.BooleanField(default=False)),
                ('last_telemetry_received', models.DateTimeField(blank=True, null=True)),
                ('telemetry_status', models.CharField(blank=True, max_length=50)),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_number', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=150)),
                ('model_name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('standard_warranty_months', models.IntegerField(default=12)),
                ('cost_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('sale_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('specifications', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='models', to='service_management.devicecategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_models', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['manufacturer', 'model_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField()),
                ('contract_type', models.CharField(choices=[('basic', 'Basic Support'), ('standard', 'Standard Support'), ('premium', 'Premium Support'), ('enterprise', 'Enterprise Support'), ('custom', 'Custom Agreement')], max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('suspended', 'Suspended'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('renewal_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('annual_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('billing_frequency', models.CharField(default='annual', max_length=20)),
                ('response_time_hours', models.IntegerField(default=24)),
                ('resolution_time_hours', models.IntegerField(blank=True, null=True)),
                ('uptime_guarantee_percent', models.DecimalField(decimal_places=2, default=Decimal('99.9'), max_digits=5)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_contracts', to='usermanagement.organization')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_contract_revenue', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField()),
                ('subject', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('waiting_customer', 'Waiting on Customer'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=30)),
                ('assigned_to', models.IntegerField(blank=True, null=True)),
                ('assigned_date', models.DateTimeField(blank=True, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('first_response_date', models.DateTimeField(blank=True, null=True)),
                ('resolution_date', models.DateTimeField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('sla_breach', models.BooleanField(default=False)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_tickets', to='service_management.devicelifecycle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='service_management.servicecontract')),
            ],
            options={
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='RMAHardware',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rma_number', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('device_shipped', 'Device Shipped to Depot'), ('received', 'Received at Depot'), ('diagnosing', 'Under Diagnosis'), ('repairing', 'Repairing'), ('replacement_shipped', 'Replacement Shipped'), ('completed', 'Completed'), ('closed', 'Closed')], default='requested', max_length=30)),
                ('failure_type', models.CharField(choices=[('doa', 'Dead on Arrival'), ('hardware_failure', 'Hardware Failure'), ('software_issue', 'Software/Firmware Issue'), ('physical_damage', 'Physical Damage'), ('intermittent', 'Intermittent Issue'), ('user_error', 'User Error')], max_length=30)),
                ('failure_description', models.TextField()),
                ('requested_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('received_date', models.DateTimeField(blank=True, null=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('is_under_warranty', models.BooleanField(default=False)),
                ('warranty_claim_number', models.CharField(blank=True, max_length=100)),
                ('replacement_shipped_date', models.DateTimeField(blank=True, null=True)),
                ('repair_action', models.CharField(blank=True, max_length=50)),
                ('repair_cost', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('return_tracking_number', models.CharField(blank=True, max_length=100)),
                ('replacement_tracking_number', models.CharField(blank=True, max_length=100)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rmas', to='service_management.devicelifecycle')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
                ('replacement_device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rma_replacements', to='service_management.devicelifecycle')),
                ('service_contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_rmas', to='service_management.servicecontract')),
                ('service_ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_rmas', to='service_management.serviceticket')),
            ],
            options={
                'ordering': ['-requested_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceStateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_state', models.CharField(max_length=20)),
                ('to_state', models.CharField(max_length=20)),
                ('changed_by', models.IntegerField()),
                ('change_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('reason', models.TextField(blank=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_history', to='service_management.devicelifecycle')),
            ],
            options={
                'ordering': ['-change_date'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProvisioningTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=150)),
                ('configuration_script', models.TextField(help_text='Automated configuration commands')),
                ('firmware_url', models.URLField(blank=True)),
                ('required_firmware_version', models.CharField(blank=True, max_length=50)),
                ('provisioning_metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provisioning_templates', to='service_management.devicemodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
            ],
            options={
                'ordering': ['template_name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceProvisioningLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provisioning_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('provisioned_by', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('success', 'Success'), ('failed', 'Failed')], max_length=20)),
                ('firmware_version_applied', models.CharField(blank=True, max_length=50)),
                ('configuration_applied', models.TextField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provisioning_logs', to='service_management.devicelifecycle')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='service_management.deviceprovisioningtemplate')),
            ],
            options={
                'ordering': ['-provisioning_date'],
            },
        ),
        migrations.AddField(
            model_name='devicelifecycle',
            name='device_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='service_management.devicemodel'),
        ),
        migrations.AddField(
            model_name='devicelifecycle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='devices', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='devicelifecycle',
            name='service_contract',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='service_management.servicecontract'),
        ),
        migrations.CreateModel(
            name='WarrantyPool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pool_name', models.CharField(max_length=150)),
                ('location', models.CharField(max_length=200)),
                ('available_quantity', models.IntegerField(default=0)),
                ('allocated_quantity', models.IntegerField(default=0)),
                ('minimum_quantity', models.IntegerField(default=0)),
                ('average_unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_pools', to='service_management.devicemodel')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_pools', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['device_model', 'pool_name'],
                'unique_together': {('organization', 'device_model', 'pool_name')},
            },
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['organization', 'status'], name='service_man_organiz_cfa1c6_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['customer_id', 'status'], name='service_man_custome_8adb08_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceticket',
            index=models.Index(fields=['priority', 'status'], name='service_man_priorit_8aea2c_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['organization', 'status'], name='service_man_organiz_b81919_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['customer_id', 'status'], name='service_man_custome_cbd3e8_idx'),
        ),
        migrations.AddIndex(
            model_name='servicecontract',
            index=models.Index(fields=['end_date', 'auto_renew'], name='service_man_end_dat_5546d5_idx'),
        ),
        migrations.AddIndex(
            model_name='rmahardware',
            index=models.Index(fields=['organization', 'status'], name='service_man_organiz_1fd611_idx'),
        ),
        migrations.AddIndex(
            model_name='rmahardware',
            index=models.Index(fields=['device', 'status'], name='service_man_device__626226_idx'),
        ),
        migrations.AddIndex(
            model_name='rmahardware',
            index=models.Index(fields=['customer_id'], name='service_man_custome_f5108f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicemodel',
            unique_together={('organization', 'model_number')},
        ),
        migrations.AddIndex(
            model_name='devicelifecycle',
            index=models.Index(fields=['organization', 'state'], name='service_man_organiz_8b61d1_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelifecycle',
            index=models.Index(fields=['customer_id', 'state'], name='service_man_custome_b766fa_idx'),
        ),
        migrations.AddIndex(
            model_name='devicelifecycle',
            index=models.Index(fields=['serial_number'], name='service_man_serial__a22fa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecategory',
            unique_together={('organization', 'code')},
        ),
    ]
