# Generated by Django 5.0.14 on 2025-11-21 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TenantBrandingConfig',
            fields=[
            ],
            options={
                'verbose_name': 'Tenant branding setting',
                'verbose_name_plural': 'Tenant branding settings',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('tenancy.tenantconfig',),
        ),
    ]
