# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_periods', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_account_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_account_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_account_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='account_type',
            field=models.ForeignKey(db_column='account_type_id', on_delete=django.db.models.deletion.PROTECT, to='accounting.accounttype'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_accounts', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='parent_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cost_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.ForeignKey(db_column='from_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='currency_exchange_rates', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.ForeignKey(db_column='to_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fiscal_years', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accountingperiod',
            name='fiscal_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='periods', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='organization_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='general_ledgers', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='journals', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='journal',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.accountingperiod'),
        ),
        migrations.AddField(
            model_name='journal',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='approval',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_journal_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journalline',
            name='reconciled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_journal_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_journal_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='journal_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='gl_entries', to='accounting.journalline'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_journal_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_journal_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='journal_types', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_journal_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.journaltype'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.journaltype'),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_journals', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recurring_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='recurring_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.recurringjournal'),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_authorities', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='purchase_account',
            field=models.ForeignKey(blank=True, db_column='purchase_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_tax_codes', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='sales_account',
            field=models.ForeignKey(blank=True, db_column='sales_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_codes', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='tax_authority',
            field=models.ForeignKey(blank=True, db_column='tax_authority_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.taxauthority'),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journalline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='authority',
            field=models.ForeignKey(blank=True, db_column='authority_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxauthority'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tax_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_types', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_tax_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='tax_type',
            field=models.ForeignKey(db_column='tax_type_id', on_delete=django.db.models.deletion.PROTECT, to='accounting.taxtype'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_voucher_configs', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_voucher_configs', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_tax_ledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'control_account_type': 'tax', 'is_control_account': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_ledger_for_voucher_configs', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='journal_type',
            field=models.ForeignKey(blank=True, db_column='journal_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.journaltype'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_mode_configs', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='account_type',
            field=models.ForeignKey(blank=True, db_column='account_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttype'),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_default_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='config',
            field=models.ForeignKey(db_column='config_id', on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='accounting.vouchermodeconfig'),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucherdefaultconfigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, db_column='default_tax_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucherdefaultconfigs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_udfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_udfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_udf_configs', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_udfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='voucher_mode',
            field=models.ForeignKey(db_column='voucher_mode_id', on_delete=django.db.models.deletion.CASCADE, related_name='udf_configs', to='accounting.vouchermodeconfig'),
        ),
        migrations.AddConstraint(
            model_name='accounttype',
            constraint=models.CheckConstraint(condition=models.Q(('root_code_step__gt', 0)), name='accounttype_root_code_step_positive'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='accounting__content_1e8bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='accounting__timesta_2c735b_idx'),
        ),
        migrations.AddConstraint(
            model_name='costcenter',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='costcenter_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['parent_account'], name='chart_of_ac_parent__b62c8b_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type'], name='chart_of_ac_account_717d3a_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['is_active'], name='chart_of_ac_is_acti_2cf4bf_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['tree_path'], name='chart_of_ac_tree_pa_1c9351_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chartofaccount',
            unique_together={('organization', 'account_code')},
        ),
        migrations.AlterUniqueTogether(
            name='currencyexchangerate',
            unique_together={('organization', 'from_currency', 'to_currency', 'rate_date')},
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='department_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['organization', 'is_current'], name='fiscal_year_organiz_33dbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['organization', 'status'], name='fiscal_year_organiz_790064_idx'),
        ),
        migrations.AddConstraint(
            model_name='fiscalyear',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='fiscalyear_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('organization', 'code')},
        ),
        migrations.AddConstraint(
            model_name='accountingperiod',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='period_start_before_end'),
        ),
        migrations.AlterUniqueTogether(
            name='accountingperiod',
            unique_together={('fiscal_year', 'period_number')},
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('journal', 'approver')},
        ),
        migrations.AlterUniqueTogether(
            name='journaltype',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('organization', 'journal_number')},
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__lt', models.F('end_date'))), name='project_start_before_end'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['account', 'transaction_date'], name='accounting__account_bfa2ca_idx'),
        ),
        migrations.AddIndex(
            model_name='generalledger',
            index=models.Index(fields=['transaction_date', 'account'], name='accounting__transac_a72e5f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringjournal',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxauthority',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='journalline',
            unique_together={('journal', 'line_number')},
        ),
        migrations.AlterUniqueTogether(
            name='taxtype',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='taxcode',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='vouchermodeconfig',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='voucherudfconfig',
            unique_together={('voucher_mode', 'field_name')},
        ),
    ]
