# Generated by Django 5.2.5 on 2025-08-20 18:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # This migration previously duplicated schema that is already created in
    # 0001_initial. To ensure fresh databases and test databases can migrate
    # cleanly we intentionally keep it as a no-op while preserving the
    # dependency structure for historical migration graphs.
    operations = []
