# Generated by Django 5.0.14 on 2025-06-04 18:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_alter_costcenter_organization'),
        ('usermanagement', '0012_remove_organization_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='usermanagement.organization'),
        ),
    ]
