# Generated by Django 5.0.14 on 2025-06-09 16:21

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0004_alter_costcenter_unique_together'),
        ('usermanagement', '0016_loginlog_usermanagem_user_id_15a248_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='departments',
                to='usermanagement.organization'
            ),
        ),
    ]
