# Generated by Django 5.0.14 on 2025-06-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0005_department_organization'),
    ]

    operations = [
    ]
