# Generated by Django 5.0.14 on 2025-06-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0006_auto_20250611_2130'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chartofaccount',
            name='currency_code',
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='accounting.currency'),
        ),
    ]
