# Generated by Django 5.0.14 on 2025-06-14 09:22

import accounting.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0008_alter_currency_options_and_more'),
        ('usermanagement', '0019_remove_appviewlog_created_by_remove_appviewlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journaltype',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='9790996759', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='fiscal_year_id',
            field=models.CharField(default=accounting.models.generate_fiscal_year_id, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_fiscal_years', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='fiscalyear',
            unique_together={('organization', 'code')},
        ),
    ]
