# Generated by Django 5.0.14 on 2025-06-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0009_alter_journaltype_options_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='8855562076', editable=False, max_length=10, unique=True),
        ),
    ]
