# Generated by Django 5.0.14 on 2025-06-15 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0010_add_accounttype_root_code_fields'),
        ('accounting', '0010_alter_fiscalyear_id'),
    ]

    operations = [
    ]
