# Generated by Django 5.0.14 on 2025-06-15 17:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0011_merge_20250615_2233'),
        ('usermanagement', '0019_remove_appviewlog_created_by_remove_appviewlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='1165633827', editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['organization', 'is_current'], name='fiscal_year_organiz_33dbdb_idx'),
        ),
        migrations.AddIndex(
            model_name='fiscalyear',
            index=models.Index(fields=['organization', 'status'], name='fiscal_year_organiz_790064_idx'),
        ),
    ]
