# Generated by Django 5.0.14 on 2025-06-20 22:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0012_alter_fiscalyear_id_and_more'),
        ('usermanagement', '0019_remove_appviewlog_created_by_remove_appviewlog_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='9862301891', editable=False, max_length=10, unique=True),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['parent_account'], name='accounting__parent__4c4691_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['account_type'], name='accounting__account_389bba_idx'),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['is_active'], name='accounting__is_acti_acf69b_idx'),
        ),
    ]
