# Generated by Django 5.0.14 on 2025-06-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0014_alter_department_options_accountingperiod_rowversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingperiod',
            name='period_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='account_type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='display_order',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='root_code_step',
            field=models.BigIntegerField(default=100, help_text='Increment step for generating top level codes'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='display_order',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='cost_center_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='rate_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0558627935', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='project',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='journal_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='journal_line_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='journalline',
            name='line_number',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='auto_numbering_next',
            field=models.BigIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='journal_type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='authority_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_code_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='tax_type_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='config_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='default_cost_center',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='default_department',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='default_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='default_project',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='display_order',
            field=models.BigIntegerField(default=0),
        ),
    ]
