# Generated by Django 5.0.14 on 2025-06-24 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0015_alter_accountingperiod_period_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='3370907204', editable=False, max_length=10, unique=True),
        ),
    ]
