# Generated by Django 5.0.14 on 2025-06-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0016_alter_chartofaccount_currency_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='8861198506', editable=False, max_length=10, unique=True),
        ),
    ]
