# Generated by Django 5.0.14 on 2025-06-27 23:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0022_alter_fiscalyear_id'),
        ('usermanagement', '0020_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='1952024976', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='VoucherUDFConfig',
            fields=[
                ('udf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Internal field name (no spaces, lowercase)', max_length=50)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], default='text', max_length=20)),
                ('scope', models.CharField(choices=[('header', 'Voucher Header'), ('line', 'Journal Line')], default='header', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('default_value', models.TextField(blank=True, null=True)),
                ('choices', models.JSONField(blank=True, help_text='For select/multiselect fields', null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_at', models.DateTimeField(blank=True, null=True)),
                ('archived_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_udfs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_udfs', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='voucher_udf_configs', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_udfs', to=settings.AUTH_USER_MODEL)),
                ('voucher_mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='udf_configs', to='accounting.vouchermodeconfig')),
            ],
            options={
                'verbose_name': 'Voucher UDF Configuration',
                'verbose_name_plural': 'Voucher UDF Configurations',
                'ordering': ['scope', 'display_order', 'field_name'],
                'unique_together': {('voucher_mode', 'field_name')},
            },
        ),
    ]
