# Generated by Django 5.0.14 on 2025-06-27 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0023_alter_fiscalyear_id_voucherudfconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4442932748', editable=False, max_length=10, unique=True),
        ),
    ]
