# Generated by Django 5.0.14 on 2025-06-28 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0024_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-journal_date', '-journal_number'], 'permissions': [('add_voucher_entry', 'Can add voucher entry'), ('change_voucher_entry', 'Can change voucher entry'), ('delete_voucher_entry', 'Can delete voucher entry'), ('view_voucher_entry', 'Can view voucher entry')]},
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='2247211703', editable=False, max_length=10, unique=True),
        ),
    ]
