# Generated by Django 5.0.14 on 2025-06-29 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0027_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4882421337', editable=False, max_length=10, unique=True),
        ),
    ]
