# Generated by Django 5.0.14 on 2025-06-29 18:23

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0028_vouchermodeconfig_ui_schema_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='5038233273', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='ui_schema',
            field=models.JSONField(blank=True, default=accounting.models.default_ui_schema),
        ),
    ]
