# Generated by Django 5.0.14 on 2025-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0029_alter_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0539827362', editable=False, max_length=10, unique=True),
        ),
    ]
