# Generated by Django 5.0.14 on 2025-06-30 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0030_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='2801750109', editable=False, max_length=10, unique=True),
        ),
    ]
