# Generated by Django 5.0.14 on 2025-06-30 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0031_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='journalline',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='1812048664', editable=False, max_length=10, unique=True),
        ),
    ]
