# Generated by Django 5.0.14 on 2025-07-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0032_journal_udf_data_journalline_udf_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='7994618846', editable=False, max_length=10, unique=True),
        ),
    ]
