# Generated by Django 5.0.14 on 2025-07-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0033_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0621318637', editable=False, max_length=10, unique=True),
        ),
    ]
