# Generated by Django 5.0.14 on 2025-07-08 19:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0035_alter_fiscalyear_id'),
        ('usermanagement', '0020_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounttype',
            options={'ordering': ['name']},
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chart_of_ac_parent__b62c8b_idx',
            old_name='accounting__parent__4c4691_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chart_of_ac_account_717d3a_idx',
            old_name='accounting__account_389bba_idx',
        ),
        migrations.RenameIndex(
            model_name='chartofaccount',
            new_name='chart_of_ac_is_acti_2cf4bf_idx',
            old_name='accounting__is_acti_acf69b_idx',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='accounttype',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='chartofaccount',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='currencyexchangerate',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='department',
            name='id',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='taxauthority',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='taxauthority',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='taxcode',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='taxtype',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='taxtype',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='vouchermodeconfig',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='vouchermodeconfig',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='vouchermodedefault',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='vouchermodedefault',
            name='is_archived',
        ),
        migrations.RemoveField(
            model_name='voucherudfconfig',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='voucherudfconfig',
            name='is_archived',
        ),
        migrations.AddField(
            model_name='accounttype',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cost_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_cost_centers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='department',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='department_id',
            field=models.BigAutoField(default=None, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='department',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_projects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_type',
            field=models.ForeignKey(db_column='account_type_id', on_delete=django.db.models.deletion.PROTECT, to='accounting.accounttype'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='currency',
            field=models.ForeignKey(blank=True, db_column='currency_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='chart_of_accounts', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='costcenter',
            name='organization',
            field=models.ForeignKey(blank=True, db_column='organization_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cost_centers', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='from_currency',
            field=models.ForeignKey(db_column='from_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_from', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='currency_exchange_rates', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='to_currency',
            field=models.ForeignKey(db_column='to_currency_id', on_delete=django.db.models.deletion.PROTECT, related_name='exchange_rates_to', to='accounting.currency'),
        ),
        migrations.AlterField(
            model_name='currencyexchangerate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='6243099949', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='journal_types', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='journaltype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_authorities', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='taxauthority',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_codes', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='purchase_account',
            field=models.ForeignKey(blank=True, db_column='purchase_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_tax_codes', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='sales_account',
            field=models.ForeignKey(blank=True, db_column='sales_account_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_tax_codes', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_authority',
            field=models.ForeignKey(blank=True, db_column='tax_authority_id', null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.taxauthority'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='tax_type',
            field=models.ForeignKey(db_column='tax_type_id', on_delete=django.db.models.deletion.PROTECT, to='accounting.taxtype'),
        ),
        migrations.AlterField(
            model_name='taxcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='authority',
            field=models.ForeignKey(blank=True, db_column='authority_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxauthority'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_types', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='taxtype',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='journal_type',
            field=models.ForeignKey(blank=True, db_column='journal_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.journaltype'),
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_mode_configs', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='vouchermodeconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='account',
            field=models.ForeignKey(blank=True, db_column='account_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='account_type',
            field=models.ForeignKey(blank=True, db_column='account_type_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounting.accounttype'),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='config',
            field=models.ForeignKey(db_column='config_id', on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to='accounting.vouchermodeconfig'),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, db_column='default_tax_code_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxcode'),
        ),
        migrations.AlterField(
            model_name='vouchermodedefault',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherudfconfig',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='voucherudfconfig',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_udf_configs', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='voucherudfconfig',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voucherudfconfig',
            name='voucher_mode',
            field=models.ForeignKey(db_column='voucher_mode_id', on_delete=django.db.models.deletion.CASCADE, related_name='udf_configs', to='accounting.vouchermodeconfig'),
        ),
        migrations.AlterModelTable(
            name='accounttype',
            table='account_type',
        ),
        migrations.AlterModelTable(
            name='chartofaccount',
            table='chart_of_account',
        ),
        migrations.AlterModelTable(
            name='costcenter',
            table='cost_center',
        ),
        migrations.AlterModelTable(
            name='currency',
            table='currency',
        ),
        migrations.AlterModelTable(
            name='currencyexchangerate',
            table='currency_exchange_rate',
        ),
        migrations.AlterModelTable(
            name='department',
            table='department',
        ),
        migrations.AlterModelTable(
            name='journaltype',
            table='journal_type',
        ),
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='taxauthority',
            table='tax_authority',
        ),
        migrations.AlterModelTable(
            name='taxcode',
            table='tax_code',
        ),
        migrations.AlterModelTable(
            name='taxtype',
            table='tax_type',
        ),
        migrations.AlterModelTable(
            name='vouchermodeconfig',
            table='voucher_mode_config',
        ),
        migrations.AlterModelTable(
            name='vouchermodedefault',
            table='voucher_mode_default',
        ),
        migrations.AlterModelTable(
            name='voucherudfconfig',
            table='voucher_udf_config',
        ),
    ]
