# Generated by Django 5.0.14 on 2025-07-18 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0036_alter_accounttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_voucher_configs', to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='default_for_voucher_configs', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_narration_template',
            field=models.TextField(blank=True, help_text='Template for default narration. Use placeholders like [PartyName].', null=True),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_tax_ledger',
            field=models.ForeignKey(blank=True, limit_choices_to={'control_account_type': 'tax', 'is_control_account': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_ledger_for_voucher_configs', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='default_voucher_mode',
            field=models.CharField(blank=True, choices=[('single_entry', 'Single Entry'), ('double_entry', 'Double Entry')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='7601046742', editable=False, max_length=10, unique=True),
        ),
    ]
