# Generated by Django 5.0.14 on 2025-07-21 15:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0037_vouchermodeconfig_default_cost_center_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accounttype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_account_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_accounts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currency',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_currencies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_exchange_rates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='department',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_departments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_general_ledgers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_journal_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_authorities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_tax_types', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_default_configs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_udfs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0170825153', editable=False, max_length=10, unique=True),
        ),
    ]
