# Generated by Django 5.0.14 on 2025-08-14 17:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0038_accounttype_archived_by_chartofaccount_archived_by_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0020_userpermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('attachment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=50)),
                ('object_id', models.PositiveIntegerField()),
                ('changes', models.JSONField()),
                ('ip_address', models.GenericIPAddressField(null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournal',
            fields=[
                ('recurring_journal_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('interval', models.PositiveSmallIntegerField(default=1, help_text='e.g., every 2 months')),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31, for monthly/quarterly/annually', null=True)),
                ('month_of_year', models.PositiveSmallIntegerField(blank=True, help_text='1-12, for annually', null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank for indefinite recurring journals', null=True)),
                ('last_run_date', models.DateField(blank=True, null=True)),
                ('next_run_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'recurring_journal',
                'ordering': ['organization', 'name'],
            },
        ),
        migrations.CreateModel(
            name='RecurringJournalLine',
            fields=[
                ('recurring_journal_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('credit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
            ],
            options={
                'ordering': ['recurring_journal', 'pk'],
            },
        ),
        migrations.RemoveField(
            model_name='journal',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='approved_by',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='archived_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='archived_by',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='locked_at',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='locked_by',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='recurring_template',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='reversal_reason',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='reversed_journal',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='source_module',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='source_reference',
        ),
        migrations.RemoveField(
            model_name='journal',
            name='udf_data',
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='condition_json',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='display_sequence',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='is_conditional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='account_code',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d{4}(?:\\.\\d{2})*$', 'Invalid COA code format.')]),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4749327275', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='generalledger',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting-approval', 'Awaiting Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='journal',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='voucherudfconfig',
            name='default_value',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='chartofaccount',
            index=models.Index(fields=['tree_path'], name='chart_of_ac_tree_pa_1c9351_idx'),
        ),
        migrations.AddField(
            model_name='approval',
            name='approver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='approval',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_recurring_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='journal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.journaltype'),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurring_journals', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='recurringjournal',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_recurring_journals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='recurringjournalline',
            name='recurring_journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.recurringjournal'),
        ),
        migrations.AlterUniqueTogether(
            name='approval',
            unique_together={('journal', 'approver')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['content_type', 'object_id'], name='accounting__content_1e8bb2_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['timestamp'], name='accounting__timesta_2c735b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='recurringjournal',
            unique_together={('organization', 'code')},
        ),
    ]