# Generated by Django 5.2.5 on 2025-08-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0039_approval_attachment_auditlog_recurringjournal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='2061594873', editable=False, max_length=10, unique=True),
        ),
    ]
