# Generated by Django 5.2.5 on 2025-08-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0040_auditlog_details_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='9917767572', editable=False, max_length=10, unique=True),
        ),
    ]
