# Generated by Django 5.2.5 on 2025-08-24 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0041_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucherudfconfig',
            name='display_sequence',
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='5354009006', editable=False, max_length=10, unique=True),
        ),
    ]
