# Generated by Django 5.2.5 on 2025-08-27 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0042_remove_voucherudfconfig_display_sequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0821959883', editable=False, max_length=10, unique=True),
        ),
    ]
