# Generated by Django 5.2.5 on 2025-08-27 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0043_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='accounttype',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='costcenter',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='currency',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='currencyexchangerate',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='fiscalyear',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='generalledger',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='rowversion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='journalline',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='taxauthority',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='taxcode',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='taxtype',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='rowversion',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vouchermodedefault',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AddField(
            model_name='voucherudfconfig',
            name='rowversion',
            field=models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4403464505', editable=False, max_length=10, unique=True),
        ),
    ]
