# Generated by Django 5.2.5 on 2025-08-27 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0044_accountingperiod_rowversion_accounttype_rowversion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='8375143922', editable=False, max_length=10, unique=True),
        ),
    ]
