# Generated by Django 5.2.5 on 2025-08-27 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0045_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4038701598', editable=False, max_length=10, unique=True),
        ),
    ]
