# Generated by Django 5.2.5 on 2025-08-29 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0047_alter_fiscalyear_id'),
        ('usermanagement', '0021_alter_permission_action'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-journal_date', '-journal_number'], 'permissions': [('add_voucher_entry', 'Can add voucher entry'), ('change_voucher_entry', 'Can change voucher entry'), ('delete_voucher_entry', 'Can delete voucher entry'), ('view_voucher_entry', 'Can view voucher entry'), ('can_submit_for_approval', 'Can submit journal for approval'), ('can_approve_journal', 'Can approve journal'), ('can_post_journal', 'Can post journal'), ('can_reverse_journal', 'Can reverse journal'), ('can_reject_journal', 'Can reject journal'), ('can_edit_journal', 'Can edit journal'), ('can_reopen_period', 'Can reopen accounting period')]},
        ),
        migrations.RenameField(
            model_name='journalline',
            old_name='exchange_rate',
            new_name='fx_rate',
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('organization', 'journal_number')},
        ),
        migrations.RemoveField(
            model_name='journalline',
            name='currency_code',
        ),
        migrations.RemoveField(
            model_name='journaltype',
            name='auto_numbering_next',
        ),
        migrations.AddField(
            model_name='journal',
            name='idempotency_key',
            field=models.CharField(blank=True, help_text='Ensures idempotent journal submissions.', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='journal',
            name='schema_version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
        migrations.AddField(
            model_name='journalline',
            name='amount_base',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='journalline',
            name='amount_txn',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='journalline',
            name='txn_currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='journal_lines_txn', to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='fiscal_year_prefix',
            field=models.BooleanField(default=False, help_text='If true, prefix with current fiscal year code.'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='sequence_next',
            field=models.BigIntegerField(default=1, help_text='Next available sequence number for auto-numbering.'),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='2259000125', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('organization', 'idempotency_key'), ('organization', 'journal_number')},
        ),
    ]
