# Generated by Django 5.2.5 on 2025-08-29 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0048_alter_journal_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0807679109', editable=False, max_length=10, unique=True),
        ),
    ]
