# Generated by Django 5.2.5 on 2025-10-12 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0050_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='swift_code',
            field=models.CharField(blank=True, help_text='SWIFT/BIC code (8 or 11 characters)', max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='1679279302', editable=False, max_length=10, unique=True),
        ),
    ]
