# Generated by Django 5.2.5 on 2025-10-12 16:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0051_chartofaccount_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='custom_code',
            field=models.CharField(blank=True, max_length=50, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}(?:\\.\\d{2})*$', 'Invalid COA code format.')]),
        ),
        migrations.AddField(
            model_name='chartofaccount',
            name='use_custom_code',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='5023047905', editable=False, max_length=10, unique=True),
        ),
    ]
