# Generated by Django 5.0.14 on 2025-12-14 11:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0059_journal_balanced_and_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherLine',
            fields=[
                ('voucher_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.BigIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('debit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('credit_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True)),
                ('tax_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('memo', models.TextField(blank=True, null=True)),
                ('udf_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['journal', 'line_number'],
            },
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='journalline_udfdata_gin',
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='balance_sheet_category',
            field=models.CharField(blank=True, choices=[('Assets', 'Assets'), ('Current Assets', 'Current Assets'), ('Fixed Assets', 'Fixed Assets'), ('Intangible Assets', 'Intangible Assets'), ('Investments', 'Investments'), ('Liabilities', 'Liabilities'), ('Current Liabilities', 'Current Liabilities'), ('Long-term Liabilities', 'Long-term Liabilities'), ('Equity', 'Equity'), ('Shareholders Equity', 'Shareholders Equity')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='cash_flow_category',
            field=models.CharField(blank=True, choices=[('Operating Activities', 'Operating Activities'), ('Investing Activities', 'Investing Activities'), ('Financing Activities', 'Financing Activities')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='classification',
            field=models.CharField(choices=[('Statement of Financial Position', 'Statement of Financial Position'), ('Statement of Profit or Loss', 'Statement of Profit or Loss'), ('Current', 'Current'), ('Non-Current', 'Non-Current'), ('Equity', 'Equity'), ('Operating', 'Operating'), ('Non-Operating', 'Non-Operating'), ('Direct', 'Direct'), ('Administrative', 'Administrative'), ('Financial', 'Financial'), ('Current Asset', 'Current Asset'), ('Default', 'Default'), ('asset', 'Asset (legacy)'), ('liability', 'Liability (legacy)'), ('equity', 'Equity (legacy)'), ('income', 'Income (legacy)'), ('expense', 'Expense (legacy)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='income_statement_category',
            field=models.CharField(blank=True, choices=[('Revenue', 'Revenue'), ('Other Income', 'Other Income'), ('Cost of Sales', 'Cost of Sales'), ('Operating Expenses', 'Operating Expenses'), ('Administrative Expenses', 'Administrative Expenses'), ('Financial Expenses', 'Financial Expenses'), ('Expense', 'Expense')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='cost_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='journal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_lines', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='voucherline',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_lines', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='voucherline',
            index=models.Index(fields=['account', 'journal'], name='vl_acc_journal_idx'),
        ),
        migrations.AddConstraint(
            model_name='voucherline',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('credit_amount', 0), ('debit_amount__gt', 0)), models.Q(('credit_amount__gt', 0), ('debit_amount', 0)), models.Q(('credit_amount', 0), ('debit_amount', 0)), _connector='OR'), name='voucherline_single_sided'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherline',
            unique_together={('journal', 'line_number')},
        ),
    ]
