# Generated by Django 5.0.14 on 2025-12-14 12:07

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0060_add_voucher_line'),
        ('usermanagement', '0030_add_auditlog_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('code', models.CharField(help_text='Short code for the voucher type', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Voucher Type',
                'verbose_name_plural': 'Voucher Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ConfigurableField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Internal field identifier', max_length=100)),
                ('default_label', models.CharField(max_length=200)),
                ('default_tooltip', models.TextField(blank=True, null=True)),
                ('default_data_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Select'), ('textarea', 'Textarea')], default='text', max_length=50)),
                ('default_visible', models.BooleanField(default=True)),
                ('default_mandatory', models.BooleanField(default=False)),
                ('default_placeholder', models.CharField(blank=True, max_length=200, null=True)),
                ('field_order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='accounting.vouchertype')),
            ],
            options={
                'verbose_name': 'Configurable Field',
                'verbose_name_plural': 'Configurable Fields',
                'ordering': ['voucher_type', 'field_order', 'name'],
                'unique_together': {('voucher_type', 'name')},
            },
        ),
        migrations.CreateModel(
            name='FieldConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_override', models.CharField(blank=True, max_length=200, null=True)),
                ('tooltip_override', models.TextField(blank=True, null=True)),
                ('data_type_override', models.CharField(blank=True, choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'DateTime'), ('boolean', 'Boolean'), ('select', 'Select'), ('textarea', 'Textarea')], max_length=50, null=True)),
                ('visible', models.BooleanField(help_text='Null means use default', null=True)),
                ('mandatory', models.BooleanField(help_text='Null means use default', null=True)),
                ('placeholder_override', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='accounting.configurablefield')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_configs', to='usermanagement.organization')),
            ],
            options={
                'verbose_name': 'Field Configuration',
                'verbose_name_plural': 'Field Configurations',
                'unique_together': {('organization', 'field')},
            },
        ),
    ]
