# Generated by Django 5.0.14 on 2025-10-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_initial'),
        ('accounting', '0052_chartofaccount_custom_code_and_more'),
        ('accounting', '0099_add_performance_indexes'),
    ]

    operations = [
    ]
