# Generated by Django 5.0.14 on 2025-10-24 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0100_merge_20251024_2340'),
        ('usermanagement', '0021_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledReport',
            fields=[
                ('report_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('report_type', models.CharField(choices=[('trial_balance', 'Trial Balance'), ('balance_sheet', 'Balance Sheet'), ('income_statement', 'Income Statement'), ('cash_flow', 'Cash Flow Statement'), ('general_ledger', 'General Ledger'), ('journal_report', 'Journal Report')], max_length=50)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('annually', 'Annually')], max_length=20)),
                ('format', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV')], default='pdf', max_length=10)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, help_text='0-6 for weekly reports', null=True)),
                ('day_of_month', models.PositiveSmallIntegerField(blank=True, help_text='1-31 for monthly reports', null=True)),
                ('time_of_day', models.TimeField(default='09:00')),
                ('recipients', models.TextField(help_text='Comma-separated email addresses')),
                ('parameters', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('last_run_date', models.DateTimeField(blank=True, null=True)),
                ('next_run_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scheduled_report',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledTaskExecution',
            fields=[
                ('execution_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('period_close', 'Period Close'), ('recurring_entry', 'Recurring Entry'), ('scheduled_report', 'Scheduled Report'), ('data_export', 'Data Export')], max_length=50)),
                ('task_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Running', 'Running'), ('Success', 'Success'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('result_message', models.TextField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('records_processed', models.IntegerField(default=0)),
                ('celery_task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'scheduled_task_execution',
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='RecurringEntry',
            fields=[
            ],
            options={
                'verbose_name': 'Recurring Entry',
                'verbose_name_plural': 'Recurring Entries',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounting.recurringjournal',),
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='idx_journal_org_status',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='idx_journal_org_created',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='idx_line_journal',
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='2356392505', editable=False, max_length=10, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('organization', 'idempotency_key'), ('organization', 'journal_number')},
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scheduled_reports', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='scheduledreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_scheduled_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='scheduledtaskexecution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_executions', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='scheduledtaskexecution',
            name='triggered_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triggered_task_executions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='scheduledtaskexecution',
            index=models.Index(fields=['organization', 'task_type', '-executed_at'], name='scheduled_t_organiz_809f76_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduledtaskexecution',
            index=models.Index(fields=['status'], name='scheduled_t_status_a2e1f5_idx'),
        ),
    ]
