# Generated by Django 5.0.14 on 2025-10-24 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0101_scheduledreport_scheduledtaskexecution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='3897798224', editable=False, max_length=10, unique=True),
        ),
    ]
