# Generated by Django 5.0.14 on 2025-10-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0103_add_performance_indexes'),
        ('accounting', '0104_add_performance_indexes'),
    ]

    operations = [
    ]
