# Generated by Django 5.0.14 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0106_journal_extra_fields'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_org_date_status_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_date_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_status_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[]
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0033372441', editable=False, max_length=10, unique=True),
        ),
    ]
