# Generated by Django 5.0.14 on 2025-11-03 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0107_remove_journal_journal_org_date_status_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='6198549912', editable=False, max_length=10, unique=True),
        ),
    ]
