# Generated by Django 5.0.14 on 2025-11-04 13:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


def _update_status_forward(apps, schema_editor):
    Journal = apps.get_model('accounting', 'Journal')
    Journal.objects.filter(status='awaiting-approval').update(status='awaiting_approval')


def _update_status_backward(apps, schema_editor):
    Journal = apps.get_model('accounting', 'Journal')
    Journal.objects.filter(status='awaiting_approval').update(status='awaiting-approval')


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0108_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='reversal_of',
            field=models.ForeignKey(blank=True, help_text='Links reversal journals back to the original entry.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reversal_entries', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='last_sequence_fiscal_year',
            field=models.ForeignKey(blank=True, help_text='Tracks the fiscal year that last consumed this sequence.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_types_last_sequence', to='accounting.fiscalyear'),
        ),
        migrations.AddField(
            model_name='journaltype',
            name='sequence_padding',
            field=models.PositiveSmallIntegerField(default=3, help_text='Total digits for sequence portion when zero-padding.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20),
        ),
        migrations.RunPython(_update_status_forward, _update_status_backward),
    ]
