# Generated by Django 5.0.14 on 2025-11-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0111_reportdefinition'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_org_date_status_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_date_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
                migrations.RunSQL(
                    sql="DROP INDEX IF EXISTS journal_status_idx;",
                    reverse_sql=migrations.RunSQL.noop,
                ),
            ],
            state_operations=[
                migrations.RemoveIndex(
                    model_name='journal',
                    name='journal_org_date_status_idx',
                ),
                migrations.RemoveIndex(
                    model_name='journal',
                    name='journal_date_idx',
                ),
                migrations.RemoveIndex(
                    model_name='journal',
                    name='journal_status_idx',
                ),
            ],
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='8347156153', editable=False, max_length=10, unique=True),
        ),
    ]
