# Generated by Django 5.0.14 on 2025-11-05 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0113_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4766943911', editable=False, max_length=10, unique=True),
        ),
    ]
