# Generated by Django 5.0.14 on 2025-11-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0115_year_end_closing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='6171071900', editable=False, max_length=10, unique=True),
        ),
    ]
