# Generated by Django 4.2.26 on 2025-11-14 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0117_customer_dimension_dimensionvalue_paymentterm_vendor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('vendor_display_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=50)),
                ('external_reference', models.CharField(blank=True, max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('base_currency_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('matched', 'Matched'), ('ready_for_posting', 'Ready for Posting'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=30)),
                ('match_status', models.CharField(choices=[('not_required', 'Not Required'), ('pending', 'Pending'), ('matched', 'Matched'), ('variance', 'Variance'), ('rejected', 'Rejected')], default='not_required', max_length=20)),
                ('po_number', models.CharField(blank=True, max_length=50)),
                ('receipt_reference', models.CharField(blank=True, max_length=50)),
                ('match_summary', models.JSONField(blank=True, default=list)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_currency', to='accounting.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='usermanagement.organization')),
                ('payment_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.paymentterm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_purchase_invoices', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices', to='accounting.vendor')),
            ],
            options={
                'db_table': 'purchase_invoice',
                'ordering': ('-invoice_date', '-invoice_id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('invoice_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('unit_cost', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('po_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_reference', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines', to='accounting.chartofaccount')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_lines', to='accounting.dimensionvalue')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.purchaseinvoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_lines', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'purchase_invoice_line',
                'ordering': ('invoice', 'line_number'),
                'unique_together': {('invoice', 'line_number')},
            },
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0346256717', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceMatch',
            fields=[
                ('match_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('po_reference', models.CharField(blank=True, max_length=100)),
                ('receipt_reference', models.CharField(blank=True, max_length=100)),
                ('expected_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('received_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('invoiced_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('unit_price_variance', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('over_receipt', 'Over Receipt'), ('short_receipt', 'Short Receipt'), ('price_variance', 'Price Variance'), ('pending', 'Pending')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_results', to='accounting.purchaseinvoice')),
                ('invoice_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_results', to='accounting.purchaseinvoiceline')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_purchase_invoice_matches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'purchase_invoice_match',
                'ordering': ('invoice', 'match_id'),
                'indexes': [models.Index(fields=['invoice', 'status'], name='purchase_in_invoice_7a8a40_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['organization', 'status'], name='purchase_in_organiz_b2055c_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseinvoice',
            index=models.Index(fields=['organization', 'match_status'], name='purchase_in_organiz_8bc457_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('organization', 'vendor', 'invoice_number')},
        ),
    ]
