# Generated by Django 4.2.26 on 2025-11-14 17:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0022_alter_permission_action'),
        ('accounting', '0118_purchaseinvoice_purchaseinvoiceline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARReceipt',
            fields=[
                ('receipt_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('receipt_number', models.CharField(max_length=50)),
                ('receipt_date', models.DateField()),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ar_receipts', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipt_currency', to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='accounting.customer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ar_receipts', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ar_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ar_receipt',
                'ordering': ('-receipt_date', '-receipt_id'),
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('invoice_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_display_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=50)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('base_currency_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('validated', 'Validated'), ('posted', 'Posted'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_invoices', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_currency', to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='accounting.customer')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoices', to='usermanagement.organization')),
                ('payment_term', models.ForeignKey(blank=True, limit_choices_to={'term_type__in': ['ar', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.paymentterm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_invoice',
                'ordering': ('-invoice_date', '-invoice_id'),
            },
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0168698821', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ARReceiptLine',
            fields=[
                ('receipt_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applied_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('discount_taken', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='accounting.salesinvoice')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.arreceipt')),
            ],
            options={
                'db_table': 'ar_receipt_line',
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('sales_invoice_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_lines', to='accounting.dimensionvalue')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.salesinvoice')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_invoice_lines', to='accounting.chartofaccount')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoice_lines', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'sales_invoice_line',
                'ordering': ('invoice', 'line_number'),
                'unique_together': {('invoice', 'line_number')},
            },
        ),
        migrations.AddIndex(
            model_name='salesinvoice',
            index=models.Index(fields=['organization', 'status'], name='sales_invoi_organiz_7db281_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesinvoice',
            unique_together={('organization', 'invoice_number')},
        ),
        migrations.AlterUniqueTogether(
            name='arreceiptline',
            unique_together={('receipt', 'invoice')},
        ),
        migrations.AlterUniqueTogether(
            name='arreceipt',
            unique_together={('organization', 'receipt_number')},
        ),
    ]
