# Generated by Django 4.2.26 on 2025-11-14 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0119_arreceipt_salesinvoice_alter_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='APPayment',
            fields=[
                ('payment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payment_number', models.CharField(max_length=30)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(default='bank_transfer', max_length=50)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('discount_taken', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('executed', 'Executed'), ('reconciled', 'Reconciled'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_bank_payments', to='accounting.chartofaccount')),
            ],
            options={
                'db_table': 'ap_payment',
                'ordering': ('-payment_date', '-payment_id'),
            },
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0874868989', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='PaymentBatch',
            fields=[
                ('batch_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('batch_number', models.CharField(max_length=30)),
                ('scheduled_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('approved', 'Approved'), ('processed', 'Processed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_batches', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_batches', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_payment_batches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_batch',
                'ordering': ('-scheduled_date', '-batch_id'),
                'unique_together': {('organization', 'batch_number')},
            },
        ),
        migrations.CreateModel(
            name='PaymentApproval',
            fields=[
                ('approval_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('approver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='accounting.appayment')),
            ],
            options={
                'db_table': 'ap_payment_approval',
                'ordering': ('-decided_at', '-approval_id'),
            },
        ),
        migrations.AddField(
            model_name='appayment',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='accounting.paymentbatch'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ap_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appayment',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ap_payments', to='accounting.journal'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ap_payments', to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='appayment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ap_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appayment',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='accounting.vendor'),
        ),
        migrations.CreateModel(
            name='APPaymentLine',
            fields=[
                ('payment_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('applied_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('discount_taken', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_lines', to='accounting.purchaseinvoice')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.appayment')),
            ],
            options={
                'db_table': 'ap_payment_line',
                'unique_together': {('payment', 'invoice')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='appayment',
            unique_together={('organization', 'payment_number')},
        ),
    ]
