# Generated by Django 4.2.26 on 2025-11-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0022_alter_permission_action'),
        ('accounting', '0120_appayment_alter_fiscalyear_id_paymentbatch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=200)),
                ('account_name', models.CharField(max_length=200)),
                ('account_number', models.CharField(max_length=64)),
                ('account_type', models.CharField(choices=[('checking', 'Checking'), ('savings', 'Savings'), ('credit', 'Credit')], default='checking', max_length=20)),
                ('routing_number', models.CharField(blank=True, max_length=50)),
                ('swift_code', models.CharField(blank=True, max_length=20)),
                ('opening_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('last_reconciled_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bank_accounts', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'bank_account',
                'ordering': ('bank_name', 'account_name'),
                'unique_together': {('organization', 'account_number')},
            },
        ),
        migrations.CreateModel(
            name='BankStatement',
            fields=[
                ('statement_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('matched', 'Matched'), ('closed', 'Closed')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='accounting.bankaccount')),
            ],
            options={
                'db_table': 'bank_statement',
                'ordering': ('-period_start',),
            },
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='5097878526', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='CashAccount',
            fields=[
                ('account_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('current_balance', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cash_accounts', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'cash_account',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('transaction_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('receipt', 'Receipt'), ('payment', 'Payment'), ('transfer', 'Transfer')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('is_reconciled', models.BooleanField(default=False)),
                ('reconciled_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bank_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounting.bankaccount')),
            ],
            options={
                'db_table': 'bank_transaction',
                'ordering': ('-transaction_date',),
            },
        ),
        migrations.CreateModel(
            name='BankStatementLine',
            fields=[
                ('statement_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_date', models.DateField()),
                ('description', models.CharField(max_length=255)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('matched_transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='statement_lines', to='accounting.banktransaction')),
                ('statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.bankstatement')),
            ],
            options={
                'db_table': 'bank_statement_line',
                'ordering': ('line_date',),
            },
        ),
    ]
