# Generated by Django 5.0.14 on 2025-11-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0121_bankaccount_bankstatement_alter_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='1242393159', editable=False, max_length=10, unique=True),
        ),
    ]
