# Generated by Django 5.0.14 on 2025-11-16 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0122_alter_fiscalyear_id'),
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalDebugPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False, help_text='When enabled, voucher entry surfaces an in-page debug panel for save flows.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='journal_debug_preference', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, help_text='Tracks who last toggled the debug mode.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_debug_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Journal Debug Preference',
                'verbose_name_plural': 'Journal Debug Preferences',
                'db_table': 'journal_debug_preferences',
            },
        ),
    ]
