# Generated by Django 5.0.14 on 2025-11-16 18:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0123_integrationevent_alter_fiscalyear_id_and_more'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSequenceConfig',
            fields=[
                ('sequence_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_credit_note', 'Sales Credit Note'), ('purchase_debit_note', 'Purchase Debit Note')], max_length=50)),
                ('prefix', models.CharField(blank=True, default='', max_length=20)),
                ('suffix', models.CharField(blank=True, default='', max_length=20)),
                ('fiscal_year_prefix', models.BooleanField(default=True, help_text='If enabled, prepend the fiscal year code before the prefix.')),
                ('reset_policy', models.CharField(choices=[('fiscal_year', 'Fiscal Year'), ('never', 'Never')], default='fiscal_year', help_text='Determines when the sequence resets back to 1.', max_length=20)),
                ('sequence_next', models.BigIntegerField(default=1)),
                ('sequence_padding', models.PositiveSmallIntegerField(default=4, help_text='Digits reserved for the numeric component.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_sequence_fiscal_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='document_sequences_last_used', to='accounting.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_sequences', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'document_sequence_config',
                'ordering': ('organization', 'document_type'),
                'unique_together': {('organization', 'document_type')},
            },
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='salesinvoice',
            name='invoice_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together={('organization', 'invoice_number')},
        ),
    ]
