# Generated by Django 5.0.14 on 2025-11-20 18:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0124_document_sequence_config'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=100)),
                ('payload', models.JSONField()),
                ('source_object', models.CharField(max_length=255)),
                ('source_id', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'integration_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4926959517', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='ApprovalWorkflow',
            fields=[
                ('workflow_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('area', models.CharField(choices=[('journal', 'Journal'), ('payment', 'Payment')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='approval_workflows', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'approval_workflow',
                'ordering': ('organization', 'name'),
                'unique_together': {('organization', 'name', 'area')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalTask',
            fields=[
                ('task_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('current_step', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype')),
                ('initiator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tasks', to='accounting.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_task',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accumulated_depreciation_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_accumulated_account', to='accounting.chartofaccount')),
                ('depreciation_expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_expense_account', to='accounting.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'asset_category',
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('asset_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('acquisition_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('salvage_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('useful_life_years', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance')], default='straight_line', max_length=32)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('active', 'Active'), ('disposed', 'Disposed')], default='active', max_length=20)),
                ('disposed_at', models.DateField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='usermanagement.organization')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='accounting.assetcategory')),
            ],
            options={
                'db_table': 'asset',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='AssetEvent',
            fields=[
                ('event_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('disposal', 'Disposal'), ('impairment', 'Impairment'), ('revaluation', 'Revaluation')], max_length=20)),
                ('event_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounting.asset')),
            ],
            options={
                'db_table': 'asset_event',
                'ordering': ('-event_date',),
            },
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('budget_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('version', models.CharField(default='01', max_length=50)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In Review'), ('approved', 'Approved'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='accounting.fiscalyear')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='budgets', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'budget',
                'ordering': ('-fiscal_year', 'name'),
                'unique_together': {('organization', 'fiscal_year', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('step_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sequence', models.PositiveIntegerField()),
                ('role', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='accounting.approvalworkflow')),
            ],
            options={
                'db_table': 'approval_step',
                'ordering': ('workflow', 'sequence'),
                'unique_together': {('workflow', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='BudgetLine',
            fields=[
                ('budget_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount_by_month', models.JSONField(blank=True, default=dict, help_text='Amount per period (keyed by 1..12)')),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.budget')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.department')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.dimensionvalue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.project')),
            ],
            options={
                'db_table': 'budget_line',
                'unique_together': {('budget', 'account', 'dimension_value', 'project', 'cost_center', 'department')},
            },
        ),
        migrations.CreateModel(
            name='TaxLiability',
            fields=[
                ('liability_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reported', 'Reported'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('reported_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tax_liabilities', to='usermanagement.organization')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='liabilities', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'tax_liability',
                'ordering': ('-period_end',),
                'unique_together': {('organization', 'tax_code', 'period_start', 'period_end')},
            },
        ),
    ]
