# Generated by Django 5.0.14 on 2025-11-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0125_integrationevent_alter_fiscalyear_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='9573883068', editable=False, max_length=10, unique=True),
        ),
    ]
