# Generated by Django 5.0.14 on 2025-11-20 19:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0126_alter_fiscalyear_id'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='8784724842', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='TaxCodeGroup',
            fields=[
                ('tax_code_group_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_code_groups', to='usermanagement.organization')),
                ('tax_codes', models.ManyToManyField(blank=True, related_name='tax_code_groups', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'tax_code_group',
                'ordering': ('name',),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineTax',
            fields=[
                ('invoice_line_tax_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('object_id', models.PositiveIntegerField()),
                ('sequence', models.PositiveIntegerField(default=1)),
                ('base_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_taxes', to='usermanagement.organization')),
                ('tax_code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoice_line_taxes', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'invoice_line_tax',
                'ordering': ('content_type', 'object_id', 'sequence'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='invoice_lin_content_ee7b1a_idx'), models.Index(fields=['organization'], name='invoice_lin_organiz_9f68a9_idx')],
                'unique_together': {('content_type', 'object_id', 'tax_code', 'sequence')},
            },
        ),
        migrations.CreateModel(
            name='TaxRule',
            fields=[
                ('tax_rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('entry_mode', models.CharField(blank=True, choices=[('sale', 'Sale'), ('purchase', 'Purchase'), ('journal', 'Journal')], max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('state_code', models.CharField(blank=True, max_length=10)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('product_category', models.CharField(blank=True, max_length=100)),
                ('customer_type', models.CharField(blank=True, max_length=100)),
                ('vendor_type', models.CharField(blank=True, max_length=100)),
                ('industry_code', models.CharField(blank=True, max_length=100)),
                ('priority', models.PositiveIntegerField(default=100)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='tax_rules', to='usermanagement.organization')),
                ('tax_code_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_rules', to='accounting.taxcodegroup')),
                ('tax_codes', models.ManyToManyField(blank=True, related_name='tax_rules', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'tax_rule',
                'ordering': ('priority', 'tax_rule_id'),
                'indexes': [models.Index(fields=['organization', 'entry_mode'], name='tax_rule_organiz_06ac78_idx'), models.Index(fields=['organization', 'country_code', 'state_code'], name='tax_rule_organiz_891a3d_idx'), models.Index(fields=['organization', 'is_active'], name='tax_rule_organiz_9f2c31_idx')],
            },
        ),
    ]
