# Generated by Django 5.0.14 on 2025-11-21 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0128_journal_approval_and_salesinvoice_ird_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0516683349', editable=False, max_length=10, unique=True),
        ),
    ]
