# Generated by Django 5.0.14 on 2025-11-21 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0129_udf_models'),
        ('accounting', '0130_alter_fiscalyear_id'),
    ]

    operations = [
    ]
