# Generated by Django 5.2.5 on 2025-11-22 15:00

from django.db import migrations, models
import django.db.models.deletion


def sync_period_organization(apps, schema_editor):
    AccountingPeriod = apps.get_model('accounting', 'AccountingPeriod')
    for period in AccountingPeriod.objects.select_related('fiscal_year').all():
        fiscal_year = period.fiscal_year
        if fiscal_year and fiscal_year.organization_id is not None:
            period.organization_id = fiscal_year.organization_id
            period.save(update_fields=['organization'])


def remove_period_organization(apps, schema_editor):
    AccountingPeriod = apps.get_model('accounting', 'AccountingPeriod')
    AccountingPeriod.objects.update(organization=None)


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0131_merge_0129_udf_models_0130_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountingperiod',
            name='organization',
            field=models.ForeignKey(
                to='usermanagement.organization',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accounting_periods',
                editable=False,
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(sync_period_organization, remove_period_organization),
        migrations.AlterField(
            model_name='accountingperiod',
            name='organization',
            field=models.ForeignKey(
                to='usermanagement.organization',
                on_delete=django.db.models.deletion.PROTECT,
                related_name='accounting_periods',
                editable=False,
            ),
        ),
    ]
