# Generated by Django 5.0.14 on 2025-11-22 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0133_salesinvoice_ird_enhancements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0592933925', editable=False, max_length=10, unique=True),
        ),
    ]
