# Generated by Django 5.0.14 on 2025-11-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0134_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='5146235574', editable=False, max_length=10, unique=True),
        ),
    ]
