# Generated by Django 5.0.14 on 2025-11-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0137_merge_0136_auto_increment_sequence_0136_materialized_journalline_summary'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyJournalLineSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_start', models.DateField()),
                ('total_debit', models.DecimalField(decimal_places=4, max_digits=19)),
                ('total_credit', models.DecimalField(decimal_places=4, max_digits=19)),
            ],
            options={
                'db_table': 'accounting_monthly_journalline_mv',
                'ordering': ['-month_start', 'account'],
                'managed': False,
            },
        ),
        migrations.RenameIndex(
            model_name='autoincrementsequence',
            new_name='auto_increm_organiz_385e69_idx',
            old_name='auto_incre_organi_51bb9f_idx',
        ),
        migrations.AlterField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_budgets', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.CASCADE, related_name='accounting_departments', to='usermanagement.organization'),
        ),
    ]
