# Generated by Django 5.0.14 on 2025-11-23 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0138_monthlyjournallinesummary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='3880589850', editable=False, max_length=10, unique=True),
        ),
    ]
