# Generated by Django 5.2.4 on 2025-11-23 17:44

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0140_alter_fiscalyear_id'),
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequenceconfig',
            name='document_type',
            field=models.CharField(choices=[('sales_order', 'Sales Order'), ('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_credit_note', 'Sales Credit Note'), ('purchase_debit_note', 'Purchase Debit Note')], max_length=50),
        ),
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='4919992484', editable=False, max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='SalesOrder',
            fields=[
                ('order_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_display_name', models.CharField(max_length=255)),
                ('order_number', models.CharField(blank=True, default='', max_length=50)),
                ('order_date', models.DateField(default=django.utils.timezone.now)),
                ('expected_ship_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('fulfilled', 'Fulfilled'), ('invoiced', 'Invoiced'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sales_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_order_currency', to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='accounting.customer')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_orders', to='accounting.salesinvoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales_orders', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sales_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'sales_order',
                'ordering': ('-order_date', '-order_id'),
            },
        ),
        migrations.CreateModel(
            name='SalesOrderLine',
            fields=[
                ('order_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.salesorder')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='accounting.chartofaccount')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_lines', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'sales_order_line',
                'ordering': ('order', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='salesorder',
            index=models.Index(fields=['organization', 'status'], name='sales_order_organiz_81edc1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='salesorder',
            unique_together={('organization', 'order_number')},
        ),
        migrations.AlterUniqueTogether(
            name='salesorderline',
            unique_together={('order', 'line_number')},
        ),
    ]
