# Generated by Django 5.0.14 on 2025-11-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0141_add_sales_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='0103894670', editable=False, max_length=10, unique=True),
        ),
    ]
