# Generated by Django 4.2.26 on 2025-11-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0142_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='6370540079', editable=False, max_length=10, unique=True),
        ),
    ]
