# Generated by Django 4.2.26 on 2025-11-24 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0022_alter_permission_action'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0145_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUIPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(default='voucher_entry', max_length=50)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_ui_preferences', to='usermanagement.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_ui_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voucher UI Preference',
                'verbose_name_plural': 'Voucher UI Preferences',
                'db_table': 'voucher_ui_preference',
                'unique_together': {('user', 'organization', 'scope')},
            },
        ),
    ]
