# Generated by Django 5.0.14 on 2025-11-24 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0146_alter_fiscalyear_id_voucheruipreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='6496010937', editable=False, max_length=10, unique=True),
        ),
    ]
