# Generated by Django 4.2.26 on 2025-11-25 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0148_alter_fiscalyear_id_irdsubmissiontask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default='7834662490', editable=False, max_length=10, unique=True),
        ),
    ]
