# Generated by Django 4.2.26 on 2025-11-25 16:38

import accounting.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0149_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fiscalyear',
            name='id',
            field=models.CharField(default=accounting.models.generate_numeric_id, editable=False, max_length=10, unique=True),
        ),
    ]
