# Generated by Django 4.2.26 on 2025-11-25 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0151_accountingperiod_is_closed_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountingperiod',
            new_name='accounting__organiz_097bfc_idx',
            old_name='accountingperiod_org_status_idx',
        ),
        migrations.RenameIndex(
            model_name='accountingperiod',
            new_name='accounting__organiz_e9646c_idx',
            old_name='accountingperiod_org_isclosed_idx',
        ),
        migrations.AlterField(
            model_name='accountingperiod',
            name='is_closed',
            field=models.BooleanField(default=False, help_text="Legacy flag mirrored from status == 'closed'."),
        ),
    ]
