# Generated by Django 5.0.14 on 2025-11-29 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0155_add_missing_ird_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='perf_coa_org_code',
        ),
        migrations.RemoveIndex(
            model_name='chartofaccount',
            name='perf_coa_org_type',
        ),
        migrations.RemoveIndex(
            model_name='generalledger',
            name='perf_gl_org_period',
        ),
        migrations.RemoveIndex(
            model_name='generalledger',
            name='perf_gl_account_period',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='perf_journal_org_date_status',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='perf_journal_org_status',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='perf_journal_date',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='perf_journal_status',
        ),
        migrations.RemoveIndex(
            model_name='journal',
            name='perf_journal_period',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='perf_jl_journal',
        ),
        migrations.RemoveIndex(
            model_name='journalline',
            name='perf_jl_account',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancellation_reason',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancelled_at',
        ),
        migrations.RemoveField(
            model_name='salesinvoice',
            name='cancelled_by',
        ),
    ]
