# Generated by Django 4.2.26 on 2025-12-02 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0156_remove_chartofaccount_perf_coa_org_code_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='salesinvoice',
            new_name='sales_invoi_organiz_fd59ef_idx',
            old_name='accounting_salesinvoice_org_ird_status_idx',
        ),
        migrations.RenameIndex(
            model_name='salesinvoice',
            new_name='sales_invoi_ird_ack_9ce127_idx',
            old_name='accounting_salesinvoice_ird_ack_idx',
        ),
    ]
