# Generated by Django 4.2.26 on 2025-12-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0157_rename_accounting_salesinvoice_org_ird_status_idx_sales_invoi_organiz_fd59ef_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='udf_data',
            field=models.JSONField(blank=True, default=dict, help_text='User-defined field values stored as JSON'),
        ),
    ]
