# Generated by Django 4.2.26 on 2025-12-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_add_inventory_management_fields'),
        ('accounting', '0158_add_coa_udf_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='grir_account',
            field=models.ForeignKey(blank=True, help_text='Goods Receipt/Invoice Receipt clearing account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice_grir', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse for receiving inventory items', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='salesinvoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse for inventory items in this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='Inventory.warehouse'),
        ),
    ]
