# Generated by Django 4.2.26 on 2025-12-04 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0159_add_inventory_management_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostDocument',
            fields=[
                ('landed_cost_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('document_date', models.DateField()),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('basis', models.CharField(choices=[('value', 'Allocate by line value'), ('quantity', 'Allocate by quantity')], default='value', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_applied', models.BooleanField(default=False)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_documents', to='accounting.currency')),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounting_landed_cost_documents', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accounting_landed_cost_documents', to='usermanagement.organization')),
                ('purchase_invoice', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_document', to='accounting.purchaseinvoice')),
            ],
            options={
                'ordering': ('-document_date', '-landed_cost_id'),
            },
        ),
        migrations.CreateModel(
            name='LandedCostLine',
            fields=[
                ('landed_cost_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('credit_account', models.ForeignKey(help_text='Source account for this cost (freight expense, duty payable, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='accounting_landed_cost_lines', to='accounting.chartofaccount')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='accounting.landedcostdocument')),
            ],
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('landed_cost_allocation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('factor', models.DecimalField(decimal_places=8, default=0, max_digits=19)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='accounting.landedcostdocument')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_allocations', to='accounting.purchaseinvoiceline')),
            ],
        ),
    ]
