# Generated by Django 5.0.14 on 2025-12-08 06:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0160_landed_cost_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='isdefault',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='currency',
            constraint=models.UniqueConstraint(condition=models.Q(('isdefault', True)), fields=('isdefault',), name='unique_default_currency'),
        ),
    ]
