# Generated by Django 5.0.14 on 2025-12-08 11:42

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0162_set_default_currency_data'),
        ('usermanagement', '0027_backfill_org_base_currency_from_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentsequenceconfig',
            name='document_type',
            field=models.CharField(choices=[('sales_order', 'Sales Order'), ('sales_invoice', 'Sales Invoice'), ('purchase_invoice', 'Purchase Invoice'), ('sales_credit_note', 'Sales Credit Note'), ('purchase_debit_note', 'Purchase Debit Note'), ('quotation', 'Quotation')], max_length=50),
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('quotation_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_display_name', models.CharField(max_length=255)),
                ('quotation_number', models.CharField(blank=True, default='', max_length=50)),
                ('quotation_date', models.DateField(default=django.utils.timezone.now)),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=1, max_digits=19)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('accepted', 'Accepted'), ('converted', 'Converted'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('terms', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('expired_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotation_currency', to='accounting.currency')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='accounting.customer')),
                ('linked_sales_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='accounting.salesinvoice')),
                ('linked_sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='source_quotations', to='accounting.salesorder')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotations', to='usermanagement.organization')),
                ('payment_term', models.ForeignKey(blank=True, limit_choices_to={'term_type__in': ['ar', 'both']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.paymentterm')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_quotations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quotation',
                'ordering': ('-quotation_date', '-quotation_id'),
            },
        ),
        migrations.CreateModel(
            name='QuotationLine',
            fields=[
                ('line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, default='')),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.costcenter')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.department')),
                ('dimension_value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.dimensionvalue')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.project')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.quotation')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.chartofaccount')),
                ('tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_lines', to='accounting.taxcode')),
            ],
            options={
                'db_table': 'quotation_line',
                'ordering': ('quotation', 'line_number'),
            },
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['organization', 'status'], name='quotation_organiz_f029e9_idx'),
        ),
        migrations.AddIndex(
            model_name='quotation',
            index=models.Index(fields=['organization', 'valid_until'], name='quotation_organiz_8cd8ba_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='quotation',
            unique_together={('organization', 'quotation_number')},
        ),
        migrations.AlterUniqueTogether(
            name='quotationline',
            unique_together={('quotation', 'line_number')},
        ),
    ]
