# Generated by ChatGPT on 2025-12-08
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0163_alter_documentsequenceconfig_document_type_quotation_and_more"),
        ("Inventory", "0004_add_inventory_management_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="salesorder",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                help_text="Default warehouse for allocation/fulfillment",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_orders",
                to="Inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="salesorderline",
            name="allocated_quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
    ]
