# Generated by Django 4.2.26 on 2025-12-08 18:03

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0028_companyconfig_invoice_template'),
        ('accounting', '0164_sales_order_allocation_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('expense_category_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_payment_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_category_payment_defaults', to='accounting.chartofaccount')),
                ('default_tax_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_code_expense_categories', to='accounting.taxcode')),
                ('expense_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_categories_expense_account', to='accounting.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expense_categories', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'expense_category',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExpenseEntry',
            fields=[
                ('expense_entry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('entry_date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=19, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('gst_applicable', models.BooleanField(default=False)),
                ('gst_amount', models.DecimalField(decimal_places=4, default=Decimal('0.00'), max_digits=19)),
                ('paid_via', models.CharField(choices=[('cash', 'Cash'), ('bank', 'Bank'), ('payable', 'Accounts Payable')], default='bank', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('awaiting_approval', 'Awaiting Approval'), ('posted', 'Posted'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='posted', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rowversion', models.BinaryField(blank=True, help_text='For MSSQL: ROWVERSION for optimistic concurrency.', null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='accounting.expensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_expense_entries', to=settings.AUTH_USER_MODEL)),
                ('journal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='accounting.journal')),
                ('journal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expense_entries', to='accounting.journaltype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_entries', to='usermanagement.organization')),
                ('payment_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expense_payment_entries', to='accounting.chartofaccount')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_expense_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expense_entry',
                'ordering': ['-entry_date', '-expense_entry_id'],
                'indexes': [models.Index(fields=['organization', 'entry_date'], name='expense_ent_organiz_76c4a2_idx'), models.Index(fields=['category'], name='expense_ent_categor_ac3d8b_idx'), models.Index(fields=['paid_via'], name='expense_ent_paid_vi_ea2530_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['organization'], name='expense_cat_organiz_bc9be6_idx'),
        ),
        migrations.AddIndex(
            model_name='expensecategory',
            index=models.Index(fields=['code'], name='expense_cat_code_5b7b7b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='expensecategory',
            unique_together={('organization', 'code')},
        ),
    ]
