# Generated by Django 5.0.14 on 2025-12-09 07:59

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0165_expensecategory_expenseentry_and_more'),
        ('usermanagement', '0028_companyconfig_invoice_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceivableReminder',
            fields=[
                ('reminder_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS/WhatsApp')], default='email', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('scheduled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('message', models.TextField()),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_receivable_reminders', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_reminders', to='accounting.customer')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='accounting.salesinvoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receivable_reminders', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_receivable_reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receivable_reminder',
                'ordering': ['-scheduled_at', '-sent_at'],
                'indexes': [models.Index(fields=['organization', 'status'], name='receivable__organiz_5f0f19_idx'), models.Index(fields=['invoice', 'sent_at'], name='receivable__invoice_1fdeb3_idx')],
            },
        ),
    ]
