# Generated by Django 5.0.14 on 2025-12-09 10:25

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0004_add_inventory_management_fields'),
        ('accounting', '0167_payablereminder'),
        ('usermanagement', '0028_companyconfig_invoice_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('delivery_note_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('customer_display_name', models.CharField(max_length=255)),
                ('note_number', models.CharField(blank=True, default='', max_length=50)),
                ('delivery_date', models.DateField(default=django.utils.timezone.now)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_delivery_notes', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='accounting.customer')),
                ('linked_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='accounting.salesinvoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='delivery_notes', to='usermanagement.organization')),
                ('sales_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='accounting.salesorder')),
                ('warehouse', models.ForeignKey(blank=True, help_text='Warehouse from which goods are dispatched', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='Inventory.warehouse')),
            ],
            options={
                'db_table': 'delivery_note',
                'ordering': ('-delivery_date', '-delivery_note_id'),
                'unique_together': {('organization', 'note_number')},
            },
        ),
        migrations.CreateModel(
            name='DeliveryNoteLine',
            fields=[
                ('delivery_note_line_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('line_number', models.PositiveIntegerField()),
                ('product_code', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='accounting.deliverynote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.product')),
            ],
            options={
                'db_table': 'delivery_note_line',
                'ordering': ('delivery_note', 'line_number'),
                'unique_together': {('delivery_note', 'line_number')},
            },
        ),
    ]
