# Generated by Django 4.2.26 on 2025-12-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0030_add_auditlog_organization'),
        ('accounting', '0168_deliverynote_deliverynoteline'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='auditlog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Audit Logs'},
        ),
        migrations.AddField(
            model_name='auditlog',
            name='content_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of record content', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='is_immutable',
            field=models.BooleanField(default=False, help_text='If True, this record cannot be modified'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='auditlog',
            name='previous_hash',
            field=models.ForeignKey(blank=True, help_text='Hash of previous audit record in chain', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.auditlog'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('export', 'Export'), ('print', 'Print'), ('approve', 'Approve'), ('reject', 'Reject'), ('post', 'Post'), ('sync', 'Sync')], max_length=50),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='changes',
            field=models.JSONField(default=dict, help_text='Diff of before/after values'),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='auditlog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='auditlog',
            unique_together={('organization', 'id')},
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['organization', 'timestamp'], name='accounting__organiz_3bf37e_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user', 'timestamp'], name='accounting__user_id_d31988_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['action'], name='accounting__action_d90ab6_idx'),
        ),
    ]
