# Generated by Django 5.0.14 on 2025-12-14 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0061_add_voucher_config_models'),
        ('accounting', '0170_generalledger_unique_line'),
    ]

    operations = [
    ]
