# Generated by Django 4.2.26 on 2025-12-14 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0171_merge_20251214_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='chartofaccount',
            name='reconcile',
            field=models.BooleanField(default=False, help_text='Allow reconciliation for this account'),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='control_account_type',
            field=models.CharField(blank=True, choices=[('accounts_receivable', 'Accounts Receivable'), ('accounts_payable', 'Accounts Payable'), ('inventory', 'Inventory'), ('fixed_assets', 'Fixed Assets'), ('payroll', 'Payroll'), ('tax', 'Tax'), ('other', 'Other')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='chartofaccount',
            name='default_tax_code',
            field=models.ForeignKey(blank=True, help_text='Default tax code applied to transactions.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts_defaults', to='accounting.taxcode'),
        ),
    ]
