# Generated by Django 4.2.26 on 2025-12-14 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0030_add_auditlog_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0172_chartofaccount_reconcile_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherConfiguration',
            fields=[
                ('config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.SlugField(help_text="Unique slug for the voucher type, e.g. 'journal', 'sales_order', 'purchase_invoice'")),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('module', models.CharField(choices=[('accounting', 'Accounting'), ('inventory', 'Inventory'), ('purchasing', 'Purchasing'), ('sales', 'Sales'), ('billing', 'Billing'), ('pos', 'Point of Sale'), ('manufacturing', 'Manufacturing'), ('hr', 'Human Resources'), ('other', 'Other')], default='accounting', max_length=20)),
                ('ui_schema', models.JSONField(blank=True, default=dict, help_text='UI schema for form building')),
                ('layout_style', models.CharField(choices=[('standard', 'Standard'), ('compact', 'Compact'), ('detailed', 'Detailed')], default='standard', max_length=20)),
                ('show_account_balances', models.BooleanField(default=True)),
                ('show_tax_details', models.BooleanField(default=True)),
                ('show_dimensions', models.BooleanField(default=True)),
                ('allow_multiple_currencies', models.BooleanField(default=False)),
                ('require_line_description', models.BooleanField(default=True)),
                ('default_currency', models.CharField(default='USD', max_length=3)),
                ('default_header', models.JSONField(blank=True, default=dict, help_text='Default values for header fields')),
                ('default_lines', models.JSONField(blank=True, default=dict, help_text='Default values for line fields')),
                ('validation_rules', models.JSONField(blank=True, default=dict, help_text='Validation rules as JSON')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default config for this code?')),
                ('is_active', models.BooleanField(default=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_configurations', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_configurations', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_voucher_configurations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'voucher_configuration',
                'indexes': [models.Index(fields=['organization', 'module'], name='voucher_con_organiz_6dea38_idx'), models.Index(fields=['code', 'is_active'], name='voucher_con_code_1bdfcd_idx')],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
