# Generated by Django 4.2.26 on 2025-12-14 18:29

from django.db import migrations


def migrate_voucher_configs(apps, schema_editor):
    """Migrate existing VoucherModeConfig to VoucherConfiguration."""
    VoucherModeConfig = apps.get_model('accounting', 'VoucherModeConfig')
    VoucherConfiguration = apps.get_model('accounting', 'VoucherConfiguration')
    VoucherModeDefault = apps.get_model('accounting', 'VoucherModeDefault')
    
    for old_config in VoucherModeConfig.objects.all():
        # Create new VoucherConfiguration
        new_config = VoucherConfiguration.objects.create(
            organization=old_config.organization,
            code=old_config.code,
            name=old_config.name,
            module='accounting',
            description=old_config.description,
            ui_schema=old_config.ui_schema or {},
            layout_style=old_config.layout_style,
            show_dimensions=old_config.show_dimensions,
            allow_multiple_currencies=old_config.allow_multiple_currencies,
            require_line_description=old_config.require_line_description,
            default_header={
                'currency': old_config.default_currency,
                'narration': old_config.default_narration_template,
            } if old_config.default_currency or old_config.default_narration_template else {},
            default_lines=[
                {
                    'account': default.account_id,
                    'account_type': default.account_type_id,
                    'debit': default.default_debit,
                    'credit': default.default_credit,
                    'amount': default.default_amount,
                    'description': default.default_description,
                }
                for default in VoucherModeDefault.objects.filter(config=old_config)
            ],
            validation_rules=old_config.validation_rules or {},
            version='1.0',
            is_active=old_config.is_active,
            created_by=old_config.created_by,
            updated_by=old_config.updated_by,
        )
        print(f"Migrated {old_config} to {new_config}")


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0173_voucherconfiguration'),
    ]

    operations = [
        migrations.RunPython(migrate_voucher_configs),
    ]
