# Generated by Django 5.0.14 on 2025-12-15 10:49

import accounting.models
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0175_add_concrete_voucher_models'),
        ('usermanagement', '0030_add_auditlog_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionTypeConfig',
            fields=[
                ('config_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('module', models.CharField(choices=[('accounting', 'Accounting'), ('purchasing', 'Purchasing'), ('sales', 'Sales'), ('inventory', 'Inventory'), ('logistics', 'Logistics'), ('other', 'Other')], default='accounting', max_length=20)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('abbreviation', models.CharField(blank=True, max_length=12)),
                ('description', models.TextField(blank=True, null=True)),
                ('numbering_strategy', models.CharField(choices=[('sequential', 'Sequential'), ('date_based', 'Date-based')], default='sequential', help_text='Determines how the sequence behaves (per document, per date, etc.)', max_length=20)),
                ('prefix_strategy', models.CharField(choices=[('static', 'Static'), ('fiscal_year', 'Fiscal Year'), ('dynamic', 'Dynamic Rule')], default='static', max_length=20)),
                ('suffix_strategy', models.CharField(choices=[('static', 'Static'), ('fiscal_year', 'Fiscal Year'), ('dynamic', 'Dynamic Rule')], default='static', max_length=20)),
                ('prefix_template', models.CharField(blank=True, max_length=32)),
                ('suffix_template', models.CharField(blank=True, max_length=32)),
                ('start_number', models.PositiveBigIntegerField(default=1)),
                ('sequence_next', models.PositiveBigIntegerField(default=1)),
                ('zero_padding', models.PositiveSmallIntegerField(default=4)),
                ('last_sequence_date', models.DateField(blank=True, null=True)),
                ('last_restart_trigger', models.DateField(blank=True, null=True)),
                ('print_after_save', models.BooleanField(default=False)),
                ('auto_print', models.BooleanField(default=False)),
                ('use_effective_date', models.BooleanField(default=True)),
                ('entry_date_default', models.CharField(choices=[('transaction', 'Transaction Date'), ('posting', 'Posting Date'), ('system', 'System Date')], default='transaction', max_length=20)),
                ('default_party_id', models.BigIntegerField(blank=True, null=True)),
                ('layout_flags', models.JSONField(default=accounting.models._default_layout_flags)),
                ('ui_schema', models.JSONField(blank=True, default=dict)),
                ('header_defaults', models.JSONField(blank=True, default=dict)),
                ('line_defaults', models.JSONField(blank=True, default=list)),
                ('validation_rules', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('default_ledger', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_type_defaults', to='accounting.chartofaccount')),
                ('legacy_journal_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transaction_types', to='accounting.journaltype')),
                ('legacy_voucher_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_transaction_types', to='accounting.vouchermodeconfig')),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='transaction_type_configs', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'transaction_type_config',
                'ordering': ['module', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NumberSuffixRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('suffix', models.CharField(max_length=32)),
                ('applicable_from', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suffix_rules', to='accounting.transactiontypeconfig')),
            ],
            options={
                'db_table': 'number_suffix_rule',
                'ordering': ['-applicable_from'],
            },
        ),
        migrations.CreateModel(
            name='NumberRestartRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('restart_from', models.PositiveBigIntegerField(default=1)),
                ('applicable_from', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restart_rules', to='accounting.transactiontypeconfig')),
            ],
            options={
                'db_table': 'number_restart_rule',
                'ordering': ['-applicable_from'],
            },
        ),
        migrations.CreateModel(
            name='NumberPrefixRule',
            fields=[
                ('rule_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('prefix', models.CharField(max_length=32)),
                ('applicable_from', models.DateField(default=django.utils.timezone.localdate)),
                ('transaction_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prefix_rules', to='accounting.transactiontypeconfig')),
            ],
            options={
                'db_table': 'number_prefix_rule',
                'ordering': ['-applicable_from'],
            },
        ),
        migrations.AddIndex(
            model_name='transactiontypeconfig',
            index=models.Index(fields=['organization', 'code'], name='transaction_organiz_e28067_idx'),
        ),
        migrations.AddIndex(
            model_name='transactiontypeconfig',
            index=models.Index(fields=['module', 'is_active'], name='transaction_module_447d40_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='transactiontypeconfig',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='numbersuffixrule',
            unique_together={('transaction_type', 'applicable_from')},
        ),
        migrations.AlterUniqueTogether(
            name='numberrestartrule',
            unique_together={('transaction_type', 'applicable_from')},
        ),
        migrations.AlterUniqueTogether(
            name='numberprefixrule',
            unique_together={('transaction_type', 'applicable_from')},
        ),
    ]
