# Generated by Django 4.2.26 on 2025-12-17 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0111_fix_reporting_functions'),
        ('accounting', '0176_transactiontypeconfig_numbersuffixrule_and_more'),
    ]

    operations = [
    ]
