# Generated by Django 4.2.26 on 2025-12-18 16:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0177_merge_20251218_0016'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='voucherconfiguration',
            options={'ordering': ['module', 'name']},
        ),
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='description',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='total_debit',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='description',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='total_debit',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='description',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='total_credit',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='total_debit',
        ),
        migrations.RenameField(
            model_name='salesordervoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='narration',
            field=models.TextField(blank=True, help_text='Description or narration', null=True),
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='narration',
            field=models.TextField(blank=True, help_text='Description or narration', null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='narration',
            field=models.TextField(blank=True, help_text='Description or narration', null=True),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='tax_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_lines', to='accounting.taxcode'),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='voucherconfiguration',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucherconfiguration',
            name='archived_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archived_voucher_configurations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='voucher_date',
            field=models.DateField(help_text='Date of the voucher'),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='voucher_number',
            field=models.CharField(help_text='Unique voucher number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Total amount for this line', max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='description',
            field=models.TextField(blank=True, help_text='Line description', null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number in the voucher'),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='voucher_date',
            field=models.DateField(help_text='Date of the voucher'),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='voucher_number',
            field=models.CharField(help_text='Unique voucher number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Total amount for this line', max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='description',
            field=models.TextField(blank=True, help_text='Line description', null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number in the voucher'),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_%(class)s_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='currency',
            field=models.CharField(default='USD', help_text='Currency code', max_length=3),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='voucher_date',
            field=models.DateField(help_text='Date of the voucher'),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='voucher_number',
            field=models.CharField(help_text='Unique voucher number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, help_text='Total amount for this line', max_digits=19),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='description',
            field=models.TextField(blank=True, help_text='Line description', null=True),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='line_number',
            field=models.PositiveIntegerField(help_text='Line number in the voucher'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='code',
            field=models.SlugField(help_text='Unique identifier for the voucher type (e.g., journal, sales_order)'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='default_header',
            field=models.JSONField(blank=True, default=dict, help_text='JSON of default header values'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='default_lines',
            field=models.JSONField(blank=True, default=list, help_text='List of default line dictionaries'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='module',
            field=models.CharField(choices=[('accounting', 'Accounting'), ('inventory', 'Inventory'), ('purchasing', 'Purchasing'), ('sales', 'Sales'), ('billing', 'Billing'), ('pos', 'Point of Sale'), ('manufacturing', 'Manufacturing'), ('hr', 'Human Resources'), ('other', 'Other')], default='accounting', help_text='Module this voucher belongs to', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='name',
            field=models.CharField(help_text='Human-readable name shown in selection dialogs', max_length=100),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='ui_schema',
            field=models.JSONField(blank=True, default=dict, help_text='JSON defining header and line fields, data types, validation rules'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='validation_rules',
            field=models.JSONField(blank=True, default=dict, help_text='Optional custom validation logic'),
        ),
        migrations.AlterField(
            model_name='voucherconfiguration',
            name='version',
            field=models.CharField(default='1.0', help_text='Configuration version', max_length=32),
        ),
        migrations.DeleteModel(
            name='ReportDefinition',
        ),
    ]
