# Generated by Django 4.2.26 on 2025-12-18 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0178_alter_voucherconfiguration_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='reference_number',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='reference_number',
            new_name='reference',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='reference_number',
            new_name='reference',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucher',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='voucher_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucherline',
            name='created_at',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucherline',
            old_name='line_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucherline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucherline',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucherline',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='purchaseordervoucherline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucher',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='voucher_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucherline',
            name='created_at',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucherline',
            old_name='line_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucherline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucherline',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucherline',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='purchasereturnvoucherline',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='configuration',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='narration',
        ),
        migrations.RemoveField(
            model_name='salesordervoucher',
            name='updated_by',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='voucher_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='salesordervoucherline',
            name='created_at',
        ),
        migrations.RenameField(
            model_name='salesordervoucherline',
            old_name='line_id',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='salesordervoucherline',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='salesordervoucherline',
            name='rate',
        ),
        migrations.RemoveField(
            model_name='salesordervoucherline',
            name='tax_code',
        ),
        migrations.RemoveField(
            model_name='salesordervoucherline',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='total_credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='total_debit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='total_credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='total_debit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='total_credit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='total_debit',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='voucher_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='line_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Approval'), ('approved', 'Approved'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='voucher_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='line_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='voucher_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='voucher_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='amount',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='line_number',
            field=models.PositiveIntegerField(),
        ),
    ]
