# Generated by Django 4.2.26 on 2025-12-18 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0179_rename_reference_number_purchaseordervoucher_reference_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='description',
            new_name='narration',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='description',
            new_name='narration',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='description',
            new_name='narration',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='reference',
            new_name='reference_number',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RenameField(
            model_name='purchaseordervoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RenameField(
            model_name='purchasereturnvoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.RenameField(
            model_name='salesordervoucher',
            old_name='id',
            new_name='voucher_id',
        ),
        migrations.RenameField(
            model_name='salesordervoucherline',
            old_name='id',
            new_name='line_id',
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='purchaseordervoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchaseordervoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='purchasereturnvoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.voucherconfiguration'),
        ),
        migrations.AddField(
            model_name='salesordervoucher',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_%(class)s', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='rate',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='tax_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salesordervoucherline',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
