# Generated by Codex on 2025-12-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0180_rename_description_purchaseordervoucher_narration_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                -- Purchase Order Voucher
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_order_voucher' AND column_name = 'reference_number'
                ) THEN
                    ALTER TABLE purchase_order_voucher ADD COLUMN reference_number varchar(100);
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_order_voucher' AND column_name = 'narration'
                ) THEN
                    ALTER TABLE purchase_order_voucher ADD COLUMN narration text;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_order_voucher' AND column_name = 'reference'
                ) THEN
                    UPDATE purchase_order_voucher
                    SET reference_number = reference
                    WHERE reference_number IS NULL AND reference IS NOT NULL;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_order_voucher' AND column_name = 'description'
                ) THEN
                    UPDATE purchase_order_voucher
                    SET narration = description
                    WHERE narration IS NULL AND description IS NOT NULL;
                END IF;

                -- Purchase Return Voucher
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_return_voucher' AND column_name = 'reference_number'
                ) THEN
                    ALTER TABLE purchase_return_voucher ADD COLUMN reference_number varchar(100);
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_return_voucher' AND column_name = 'narration'
                ) THEN
                    ALTER TABLE purchase_return_voucher ADD COLUMN narration text;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_return_voucher' AND column_name = 'reference'
                ) THEN
                    UPDATE purchase_return_voucher
                    SET reference_number = reference
                    WHERE reference_number IS NULL AND reference IS NOT NULL;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_return_voucher' AND column_name = 'description'
                ) THEN
                    UPDATE purchase_return_voucher
                    SET narration = description
                    WHERE narration IS NULL AND description IS NOT NULL;
                END IF;

                -- Sales Order Voucher
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_order_voucher' AND column_name = 'reference_number'
                ) THEN
                    ALTER TABLE sales_order_voucher ADD COLUMN reference_number varchar(100);
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_order_voucher' AND column_name = 'narration'
                ) THEN
                    ALTER TABLE sales_order_voucher ADD COLUMN narration text;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_order_voucher' AND column_name = 'reference'
                ) THEN
                    UPDATE sales_order_voucher
                    SET reference_number = reference
                    WHERE reference_number IS NULL AND reference IS NOT NULL;
                END IF;
                IF EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_order_voucher' AND column_name = 'description'
                ) THEN
                    UPDATE sales_order_voucher
                    SET narration = description
                    WHERE narration IS NULL AND description IS NOT NULL;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
