# Generated by Codex on 2025-12-19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0181_add_reference_number_narration_columns'),
    ]

    operations = [
        migrations.RunSQL(
            """
            DO $$
            BEGIN
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_order_voucher' AND column_name = 'configuration_id'
                ) THEN
                    ALTER TABLE purchase_order_voucher ADD COLUMN configuration_id bigint;
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'purchase_return_voucher' AND column_name = 'configuration_id'
                ) THEN
                    ALTER TABLE purchase_return_voucher ADD COLUMN configuration_id bigint;
                END IF;
                IF NOT EXISTS (
                    SELECT 1 FROM information_schema.columns
                    WHERE table_name = 'sales_order_voucher' AND column_name = 'configuration_id'
                ) THEN
                    ALTER TABLE sales_order_voucher ADD COLUMN configuration_id bigint;
                END IF;
            END $$;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
