# Generated by Django 4.2.26 on 2025-12-19 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0182_add_configuration_id_columns'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='voucher_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchaseordervoucherline',
            name='line_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='voucher_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucherline',
            name='line_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='voucher_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salesordervoucherline',
            name='line_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
