# Generated by Django 4.2.26 on 2025-12-20 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0184_unify_voucher_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.vouchermodeconfig'),
        ),
        migrations.AlterField(
            model_name='purchasereturnvoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.vouchermodeconfig'),
        ),
        migrations.AlterField(
            model_name='salesordervoucher',
            name='configuration',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_vouchers', to='accounting.vouchermodeconfig'),
        ),
    ]
