# Generated by Codex on 2025-12-20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0185_alter_purchaseordervoucher_configuration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vouchermodeconfig",
            name="ui_schema",
        ),
    ]
