# Generated by Django 4.2.26 on 2025-12-20 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0189_clear_transaction_type_ui_schema'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voucherprocess',
            new_name='voucher_pro_journal_b37e44_idx',
            old_name='voucher_proc_journal_status_idx',
        ),
    ]
