# Generated by Django 4.2.26 on 2025-12-21 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0190_rename_voucher_proc_journal_status_idx_voucher_pro_journal_b37e44_idx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currency',
            name='isdefault',
        ),
    ]
