# Generated by Django 4.2.26 on 2025-12-21 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0030_add_auditlog_organization'),
        ('accounting', '0191_remove_currency_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='isdefault',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=255)),
                ('area', models.CharField(blank=True, help_text='Geographic area covered by the agent', max_length=128)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('commission_rate', models.DecimalField(decimal_places=2, default=0, help_text='Default commission %', max_digits=5)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'agent',
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
