# Generated by Django 4.2.26 on 2025-12-21 16:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0005_enhance_purchase_invoice_models'),
        ('Inventory', '0013_alter_product_costing_method'),
        ('accounting', '0192_currency_isdefault_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='additional_charges_total',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='agent_area',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_date_bs',
            field=models.CharField(blank=True, help_text='Date in BS calendar', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='narration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('credit', 'Credit'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], default='credit', max_length=32),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='Header level default purchase account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices_header_acct', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, help_text='Link to purchase order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices_accounting', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rounding_adjustment',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Vendor/Supplier invoice number', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='input_vat_account',
            field=models.ForeignKey(blank=True, help_text='Override VAT account for this line', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_line_vat_override', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='product',
            field=models.ForeignKey(blank=True, help_text='Product reference for inventory tracking', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines_product', to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='VAT rate percentage', max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoiceline',
            name='warehouse',
            field=models.ForeignKey(blank=True, help_text='Warehouse for inventory receipt', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoice_lines_warehouse', to='Inventory.warehouse'),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=4, help_text='Positive for charges, negative for discounts', max_digits=19)),
                ('is_taxable', models.BooleanField(default=False, help_text='Apply VAT to this charge?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gl_account', models.ForeignKey(help_text='GL Account to post this charge', on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='accounting.purchaseinvoice')),
            ],
            options={
                'db_table': 'purchase_invoice_additional_charge',
                'ordering': ('invoice', 'id'),
            },
        ),
    ]
