# Generated by Django 4.2.26 on 2025-12-22 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0193_enhance_purchase_invoice_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchermodeconfig',
            name='ui_profile',
            field=models.CharField(blank=True, help_text='Optional UI profile name (e.g. purchase_invoice_v1)', max_length=100, null=True),
        ),
    ]
