# Generated by Django 4.2.26 on 2025-12-23 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0013_alter_product_costing_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usermanagement', '0030_add_auditlog_organization'),
        ('accounting', '0194_vouchermodeconfig_ui_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('pricing_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('price_type', models.CharField(choices=[('standard', 'Standard Price'), ('special', 'Special Price'), ('contract', 'Contract Price')], default='standard', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=19)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage'), ('amount', 'Fixed Amount')], default='percentage', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('effective_from', models.DateField(blank=True, null=True)),
                ('effective_to', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('priority', models.PositiveIntegerField(default=1, help_text='Higher priority takes precedence')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_pricings', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pricings', to='accounting.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='usermanagement.organization')),
                ('party', models.ForeignKey(help_text='Vendor or customer for party-specific pricing', on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='accounting.vendor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='Inventory.product')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_pricings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pricing',
                'ordering': ('-priority', '-effective_from'),
                'indexes': [models.Index(fields=['organization', 'product', 'party'], name='pricing_organiz_ce1745_idx'), models.Index(fields=['organization', 'is_active', 'effective_from', 'effective_to'], name='pricing_organiz_1828ad_idx')],
                'unique_together': {('organization', 'product', 'party', 'price_type')},
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('area_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('region', models.CharField(blank=True, help_text='Broader region this area belongs to', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_areas', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='usermanagement.organization')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_areas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'area',
                'ordering': ('name',),
                'unique_together': {('organization', 'code')},
            },
        ),
    ]
