# Generated by Django 4.2.26 on 2025-12-24 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
        ('accounting', '0195_pricing_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='accounting.agent'),
        ),
        migrations.AddField(
            model_name='customer',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'AREA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='locations.locationnode'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='accounting.agent'),
        ),
        migrations.AddField(
            model_name='vendor',
            name='area',
            field=models.ForeignKey(blank=True, limit_choices_to={'type': 'AREA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendors', to='locations.locationnode'),
        ),
        migrations.RunPython(
            lambda apps, schema_editor: apps.get_model('accounting', 'Agent').objects.update(area=None),
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='agent',
            name='area',
            field=models.ForeignKey(blank=True, help_text='Geographic area covered by the agent', limit_choices_to={'type': 'AREA'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agents', to='locations.locationnode'),
        ),
    ]
