# Generated by Django 4.2.26 on 2025-12-24 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0196_customer_agent_customer_area_vendor_agent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp for optimistic concurrency control'),
        ),
    ]
