# Generated by Django 4.2.26 on 2025-12-26 00:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0197_add_modified_at_to_journal'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='ap_outstanding_balance',
            field=models.DecimalField(
                default=Decimal('0.00'),
                decimal_places=4,
                help_text='Cached outstanding AP balance across posted vendor bills minus executed payments.',
                max_digits=19,
            ),
        ),
    ]

