# Generated by Django 4.2.26 on 2025-12-22 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0030_add_auditlog_organization'),
        ('voucher_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherUDFConfig',
            fields=[
                ('udf_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('field_name', models.CharField(help_text='Internal field name (no spaces, lowercase)', max_length=50)),
                ('display_name', models.CharField(help_text='User-friendly display name', max_length=100)),
                ('field_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('date', 'Date'), ('datetime', 'Date & Time'), ('select', 'Dropdown'), ('multiselect', 'Multi-Select'), ('checkbox', 'Checkbox'), ('textarea', 'Text Area'), ('email', 'Email'), ('phone', 'Phone'), ('url', 'URL')], default='text', max_length=20)),
                ('scope', models.CharField(choices=[('header', 'Voucher Header'), ('line', 'Journal Line')], default='header', max_length=10)),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('default_value', models.CharField(blank=True, max_length=255, null=True)),
                ('choices', models.JSONField(blank=True, help_text='For select/multiselect fields', null=True)),
                ('min_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('max_value', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('min_length', models.IntegerField(blank=True, null=True)),
                ('max_length', models.IntegerField(blank=True, null=True)),
                ('validation_regex', models.CharField(blank=True, max_length=255, null=True)),
                ('help_text', models.TextField(blank=True, null=True)),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(db_column='organization_id', on_delete=django.db.models.deletion.PROTECT, related_name='voucher_config_udf_configs', to='usermanagement.organization')),
                ('voucher_config', models.ForeignKey(db_column='voucher_config_id', on_delete=django.db.models.deletion.CASCADE, related_name='udf_configs', to='voucher_config.voucherconfigmaster')),
            ],
            options={
                'verbose_name': 'Voucher Config UDF Configuration',
                'verbose_name_plural': 'Voucher Config UDF Configurations',
                'db_table': 'voucher_config_udf_config',
                'ordering': ['scope', 'display_order', 'field_name'],
                'unique_together': {('voucher_config', 'field_name')},
            },
        ),
    ]
