# Generated by Django 5.0.14 on 2025-06-30 17:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, help_text='Voucher type code, e.g. PAYMENT', max_length=64)),
                ('version', models.CharField(default='1.0', help_text='Schema version string or number', max_length=32)),
                ('content', models.JSONField(help_text='Full UI schema as JSON')),
                ('last_modified', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True, help_text='Is this schema active for this code?')),
                ('source', models.CharField(default='db', help_text='db or file', max_length=16)),
                ('git_sha', models.CharField(blank=True, help_text='Git SHA for auditability', max_length=40, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_voucher_schemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_modified'],
                'indexes': [models.Index(fields=['code', 'is_active'], name='voucher_sch_code_0268e2_idx')],
                'unique_together': {('code', 'version')},
            },
        ),
    ]
