# Generated by Django 4.2.26 on 2025-11-25 10:04

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usermanagement', '0023_organization_address_organization_fiscal_year_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0147_alter_fiscalyear_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CylinderSKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('state', models.CharField(choices=[('filled', 'Filled'), ('empty', 'Empty')], max_length=10)),
                ('code', models.CharField(max_length=32)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('organization', 'code'),
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=150)),
                ('contact_person', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.TextField(blank=True)),
                ('tax_id', models.CharField(blank=True, max_length=50)),
                ('credit_limit', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('organization', 'company_code'),
                'unique_together': {('organization', 'company_code')},
            },
        ),
        migrations.CreateModel(
            name='LpgProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('is_bulk', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('organization', 'code'),
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='SalesInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('invoice_no', models.CharField(max_length=50)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('bank', 'Bank')], default='cash', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('empty_cylinders_collected', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='lpg_vertical.dealer')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('posted_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lpg_sales_invoices', to='accounting.journal')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'unique_together': {('organization', 'invoice_no')},
            },
        ),
        migrations.CreateModel(
            name='TransportProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('contact', models.CharField(blank=True, max_length=150)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('organization', 'name'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(max_length=50)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='lpg_vertical.transportprovider')),
            ],
            options={
                'ordering': ('organization', 'number'),
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='SalesInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_rate', models.DecimalField(decimal_places=3, default=0, max_digits=6)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('cylinder_sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lpg_vertical.cylindersku')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lpg_vertical.salesinvoice')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lpg_vertical.lpgproduct')),
            ],
            options={
                'ordering': ('invoice', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LogisticsTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('from_location', models.CharField(max_length=128)),
                ('to_location', models.CharField(max_length=128)),
                ('cylinder_count', models.PositiveIntegerField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ref_doc_type', models.CharField(blank=True, max_length=50)),
                ('ref_doc_id', models.IntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=12)),
                ('cylinder_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='logistics_trips', to='lpg_vertical.cylindersku')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('posted_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lpg_logistics_trips', to='accounting.journal')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='lpg_vertical.transportprovider')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='lpg_vertical.vehicle')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='InventoryMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12)),
                ('movement_type', models.CharField(choices=[('purchase_noc', 'NOC Purchase'), ('sale', 'Sale'), ('empty_collection', 'Empty Collection'), ('refill', 'Refill'), ('damage_loss', 'Damage/Loss'), ('transfer_out', 'Transfer Out'), ('transfer_in', 'Transfer In')], max_length=20)),
                ('source_location', models.CharField(blank=True, max_length=128)),
                ('dest_location', models.CharField(blank=True, max_length=128)),
                ('ref_doc_type', models.CharField(blank=True, max_length=50)),
                ('ref_doc_id', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cylinder_sku', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='lpg_vertical.cylindersku')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('-date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='CylinderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Display name, e.g. 14.2 kg', max_length=50)),
                ('kg_per_cylinder', models.DecimalField(decimal_places=3, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('organization', 'kg_per_cylinder'),
                'unique_together': {('organization', 'name')},
            },
        ),
        migrations.AddField(
            model_name='cylindersku',
            name='cylinder_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skus', to='lpg_vertical.cylindertype'),
        ),
        migrations.AddField(
            model_name='cylindersku',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.CreateModel(
            name='NocPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bill_no', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('quantity_mt', models.DecimalField(decimal_places=3, max_digits=12)),
                ('rate_per_mt', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transport_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('receipt_location', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted to Accounting/Inventory')], default='draft', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('allocation_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('posted_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lpg_noc_purchases', to='accounting.journal')),
            ],
            options={
                'ordering': ('-date', '-id'),
                'unique_together': {('organization', 'bill_no')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='cylindersku',
            unique_together={('organization', 'code')},
        ),
        migrations.CreateModel(
            name='ConversionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mt_fraction_per_cylinder', models.DecimalField(decimal_places=6, help_text='How many metric tons are consumed per 1 cylinder of this type.', max_digits=10)),
                ('is_default', models.BooleanField(default=True, help_text='Mark the default rule per cylinder type for allocation logic.')),
                ('cylinder_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_rules', to='lpg_vertical.cylindertype')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'unique_together': {('organization', 'cylinder_type', 'is_default')},
            },
        ),
    ]
