# Generated by Django 4.2.26 on 2025-11-24 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0143_alter_fiscalyear_id'),
        ('usermanagement', '0022_alter_permission_action'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeferredRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField(blank=True, null=True)),
                ('contract_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('deferred_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('recognized_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('service_period_start', models.DateField()),
                ('service_period_end', models.DateField()),
                ('recognition_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('milestone', 'Milestone-Based'), ('usage', 'Usage-Based'), ('deliverable', 'Deliverable-Based')], default='straight_line', max_length=20)),
                ('is_fully_recognized', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deferred_revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenues', to='accounting.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenues', to='usermanagement.organization')),
                ('revenue_account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recognized_revenues', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['service_period_start'],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('plan_type', models.CharField(choices=[('recurring', 'Recurring'), ('usage_based', 'Usage-Based'), ('tiered', 'Tiered Usage'), ('hybrid', 'Hybrid (Recurring + Usage)')], default='recurring', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('semi_annual', 'Semi-Annual'), ('annual', 'Annual'), ('one_time', 'One-Time')], default='monthly', max_length=20)),
                ('base_price', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('currency_code', models.CharField(default='USD', max_length=3)),
                ('trial_period_days', models.IntegerField(default=0)),
                ('setup_fee', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('minimum_commitment_months', models.IntegerField(default=0)),
                ('auto_renew', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deferred_revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenue_plans', to='accounting.chartofaccount')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscription_plans', to='usermanagement.organization')),
                ('revenue_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_revenue_plans', to='accounting.chartofaccount')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.CreateModel(
            name='UsageTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=100)),
                ('min_quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('max_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('price_per_unit', models.DecimalField(decimal_places=4, max_digits=19)),
                ('overage_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_tiers', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['subscription_plan', 'min_quantity'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_number', models.CharField(max_length=50, unique=True)),
                ('customer_id', models.IntegerField()),
                ('status', models.CharField(choices=[('trial', 'Trial'), ('active', 'Active'), ('suspended', 'Suspended'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='trial', max_length=20)),
                ('start_date', models.DateField()),
                ('trial_end_date', models.DateField(blank=True, null=True)),
                ('current_period_start', models.DateField()),
                ('current_period_end', models.DateField()),
                ('next_billing_date', models.DateField()),
                ('cancellation_date', models.DateField(blank=True, null=True)),
                ('cancellation_reason', models.TextField(blank=True)),
                ('custom_price', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('contract_term_months', models.IntegerField(blank=True, null=True)),
                ('contract_end_date', models.DateField(blank=True, null=True)),
                ('auto_renew', models.BooleanField(default=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='usermanagement.organization')),
                ('subscription_plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='subscriptions', to='billing.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilestoneRevenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milestone_number', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('deliverable', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('invoiced', 'Invoiced'), ('recognized', 'Revenue Recognized')], default='pending', max_length=20)),
                ('milestone_value', models.DecimalField(decimal_places=4, max_digits=19)),
                ('recognized_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deferred_revenue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='milestones', to='billing.deferredrevenue')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
            ],
            options={
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='DeferredRevenueSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recognition_date', models.DateField()),
                ('recognition_amount', models.DecimalField(decimal_places=4, max_digits=19)),
                ('is_recognized', models.BooleanField(default=False)),
                ('journal_entry_id', models.IntegerField(blank=True, null=True)),
                ('recognized_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('deferred_revenue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_lines', to='billing.deferredrevenue')),
            ],
            options={
                'ordering': ['recognition_date'],
            },
        ),
        migrations.AddField(
            model_name='deferredrevenue',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deferred_revenues', to='billing.subscription'),
        ),
        migrations.CreateModel(
            name='SubscriptionUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_date', models.DateField()),
                ('usage_type', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=15)),
                ('unit_of_measure', models.CharField(max_length=50)),
                ('calculated_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('is_billed', models.BooleanField(default=False)),
                ('billed_invoice_id', models.IntegerField(blank=True, null=True)),
                ('recorded_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_records', to='billing.subscription')),
                ('tier_applied', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.usagetier')),
            ],
            options={
                'ordering': ['-usage_date'],
                'indexes': [models.Index(fields=['subscription', 'usage_date', 'is_billed'], name='billing_sub_subscri_bee7d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubscriptionInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.IntegerField()),
                ('invoice_number', models.CharField(max_length=50)),
                ('billing_period_start', models.DateField()),
                ('billing_period_end', models.DateField()),
                ('subscription_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('usage_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('setup_fee', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='invoices', to='billing.subscription')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'subscription'], name='billing_sub_organiz_44ed34_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['organization', 'customer_id', 'status'], name='billing_sub_organiz_b6a0ab_idx'),
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['next_billing_date', 'status'], name='billing_sub_next_bi_aac88e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='milestonerevenue',
            unique_together={('organization', 'milestone_number')},
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['organization', 'is_fully_recognized'], name='billing_def_organiz_718dec_idx'),
        ),
        migrations.AddIndex(
            model_name='deferredrevenue',
            index=models.Index(fields=['service_period_start', 'service_period_end'], name='billing_def_service_1ce5dd_idx'),
        ),
    ]
