# Generated by Django 4.2.26 on 2025-12-10 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0002_tenantbrandingconfig'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('local', 'Local Storage'), ('s3', 'Amazon S3'), ('gcs', 'Google Cloud Storage'), ('gdrive', 'Google Drive'), ('dropbox', 'Dropbox')], default='local', max_length=20)),
                ('config', models.JSONField(default=dict, help_text='Configuration details like bucket name, folder, etc.')),
                ('credentials', models.JSONField(default=dict, help_text='Encrypted credentials or token references')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='BackupPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('manual', 'Manual Only')], default='daily', max_length=20)),
                ('notify_emails', models.TextField(blank=True, help_text='Comma separated email addresses')),
                ('retain_days', models.IntegerField(default=7, help_text='Number of days to keep backups')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='backups.backupdestination')),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='backup_preference', to='tenancy.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='BackupJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('kind', models.CharField(choices=[('manual', 'Manual'), ('auto', 'Automated')], default='manual', max_length=20)),
                ('mode', models.CharField(choices=[('pg_dump', 'PostgreSQL Dump'), ('csv_zip', 'CSV Zip'), ('json', 'JSON Dump')], default='pg_dump', max_length=20)),
                ('storage_type', models.CharField(default='local', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=500, null=True)),
                ('file_size', models.BigIntegerField(blank=True, null=True)),
                ('checksum', models.CharField(blank=True, max_length=64, null=True)),
                ('encryption_method', models.CharField(default='none', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='backups', to='tenancy.tenant')),
            ],
        ),
    ]
