# Generated by Django 4.2.26 on 2025-11-30 17:00

from django.db import migrations, models
import django.db.models.deletion
import ird_integration.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit_note_number', models.CharField(max_length=50, unique=True)),
                ('credit_note_date', models.DateField()),
                ('fiscal_year', models.CharField(max_length=20)),
                ('reason_for_return', models.CharField(max_length=255)),
                ('buyer_pan', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(max_length=200)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_sales_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excisable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_sales_hst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_for_esf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('export_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_exempted_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Credit Note',
                'verbose_name_plural': 'Credit Notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('invoice_date', models.DateField()),
                ('fiscal_year', models.CharField(max_length=20)),
                ('buyer_pan', models.CharField(max_length=20)),
                ('buyer_name', models.CharField(max_length=200)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_sales_vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excisable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('excise', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('taxable_sales_hst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hst', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_for_esf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('esf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('export_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_exempted_sales', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IRDSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_pan', models.CharField(max_length=20, verbose_name='Seller PAN')),
                ('username', models.CharField(max_length=100, verbose_name='IRD Username')),
                ('password', ird_integration.models.EncryptedCharField(max_length=100, verbose_name='IRD Password')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IRD Settings',
                'verbose_name_plural': 'IRD Settings',
            },
        ),
        migrations.CreateModel(
            name='IRDLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('request_payload', models.TextField()),
                ('response_payload', models.TextField()),
                ('success', models.BooleanField(default=False)),
                ('credit_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ird_logs', to='ird_integration.creditnote')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ird_logs', to='ird_integration.invoice')),
            ],
            options={
                'verbose_name': 'IRD API Log',
                'verbose_name_plural': 'IRD API Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='creditnote',
            name='ref_invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='ird_integration.invoice'),
        ),
    ]
