# Generated by Django 4.2.26 on 2025-12-02 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0158_add_coa_udf_data'),
        ('ird_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='irdlog',
            name='sales_invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ird_logs', to='accounting.salesinvoice'),
        ),
    ]
