# Generated by Django 5.0.14 on 2025-11-23 15:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0001_initial'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetdepreciationschedule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='benefitenrollment',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='billofmaterial',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='crmlead',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='fixedasset',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='fixedassetcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='integrationendpoint',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='leaverequest',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='localeconfig',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='opportunity',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='payrollcycle',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='payrollentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='posdevice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='position',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
    ]
