# Generated by Django 5.0.14 on 2025-11-23 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0004_payroll_components_and_runs'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycomponent',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='payrollrun',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='payrollrunline',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
    ]
