# Generated by Django 5.0.14 on 2025-11-23 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enterprise', '0005_alter_paycomponent_organization_and_more'),
        ('enterprise', '0007_integration_and_tax_models'),
    ]

    operations = [
    ]
