# Generated by Django 4.2.26 on 2025-11-24 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0022_alter_permission_action'),
        ('enterprise', '0008_merge_20251124_0026'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='QCCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=50)),
                ('checkpoint_type', models.CharField(choices=[('incoming', 'Incoming Material Inspection'), ('in_process', 'In-Process Inspection'), ('final', 'Final Inspection'), ('sampling', 'Statistical Sampling')], max_length=20)),
                ('test_method', models.CharField(choices=[('visual', 'Visual Inspection'), ('dimensional', 'Dimensional Measurement'), ('functional', 'Functional Test'), ('destructive', 'Destructive Test'), ('non_destructive', 'Non-Destructive Test')], max_length=30)),
                ('specification', models.TextField()),
                ('sample_size', models.IntegerField(default=1)),
                ('is_mandatory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='integrationcredential',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='routing',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='taxregime',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='webhooksubscription',
            name='token',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='workcenter',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.AlterField(
            model_name='workorderoperation',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization'),
        ),
        migrations.CreateModel(
            name='YieldTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('planned_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('actual_quantity', models.DecimalField(decimal_places=4, max_digits=12)),
                ('scrap_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('rework_quantity', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('yield_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('scrap_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('recorded_by', models.IntegerField()),
                ('recorded_date', models.DateTimeField()),
                ('notes', models.TextField(blank=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='yields', to='enterprise.workorderoperation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='yield_tracking', to='enterprise.workorder')),
            ],
            options={
                'ordering': ['-recorded_date'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderCosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('standard_material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('actual_material_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('standard_labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('actual_labor_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('standard_overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('actual_overhead_cost', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('variance_material', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('variance_labor', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('variance_overhead', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='costing', to='enterprise.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('capacity_hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='enterprise.productioncalendar')),
            ],
            options={
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='QCInspectionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inspection_number', models.CharField(max_length=50, unique=True)),
                ('batch_number', models.CharField(blank=True, max_length=100)),
                ('inspector_id', models.IntegerField()),
                ('inspection_date', models.DateTimeField()),
                ('result', models.CharField(choices=[('pass', 'Pass'), ('fail', 'Fail'), ('conditional', 'Conditional Pass')], max_length=20)),
                ('quantity_inspected', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_passed', models.DecimalField(decimal_places=4, max_digits=12)),
                ('quantity_failed', models.DecimalField(decimal_places=4, max_digits=12)),
                ('measurements', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('qc_checkpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='enterprise.qccheckpoint')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_inspections', to='enterprise.workorder')),
            ],
            options={
                'ordering': ['-inspection_date'],
            },
        ),
        migrations.AddField(
            model_name='qccheckpoint',
            name='routing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='qc_checkpoints', to='enterprise.routing'),
        ),
        migrations.AddField(
            model_name='qccheckpoint',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qc_checkpoints', to='enterprise.workcenter'),
        ),
        migrations.CreateModel(
            name='ProductionHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('holiday_date', models.DateField()),
                ('is_recurring', models.BooleanField(default=False)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holidays', to='enterprise.productioncalendar')),
            ],
            options={
                'ordering': ['holiday_date'],
            },
        ),
        migrations.AddField(
            model_name='productioncalendar',
            name='work_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calendars', to='enterprise.workcenter'),
        ),
        migrations.CreateModel(
            name='NCR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ncr_number', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('major', 'Major'), ('minor', 'Minor')], max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('investigating', 'Under Investigation'), ('corrective_action', 'Corrective Action'), ('closed', 'Closed'), ('rejected', 'Rejected')], default='open', max_length=30)),
                ('reported_by', models.IntegerField()),
                ('reported_date', models.DateTimeField()),
                ('assigned_to', models.IntegerField(blank=True, null=True)),
                ('root_cause', models.TextField(blank=True)),
                ('corrective_action', models.TextField(blank=True)),
                ('preventive_action', models.TextField(blank=True)),
                ('closed_by', models.IntegerField(blank=True, null=True)),
                ('closed_date', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
                ('qc_inspection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ncrs', to='enterprise.qcinspectionrecord')),
                ('work_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ncrs', to='enterprise.workorder')),
            ],
            options={
                'ordering': ['-reported_date'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='qccheckpoint',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='productioncalendar',
            unique_together={('organization', 'code')},
        ),
        migrations.CreateModel(
            name='BOMRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_number', models.CharField(max_length=20)),
                ('effective_date', models.DateField()),
                ('obsolete_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('change_reason', models.TextField(blank=True)),
                ('changed_by', models.IntegerField(blank=True, null=True)),
                ('approved_by', models.IntegerField(blank=True, null=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('eco_number', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('bill_of_material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='enterprise.billofmaterial')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='usermanagement.organization')),
            ],
            options={
                'ordering': ['-effective_date'],
                'unique_together': {('bill_of_material', 'revision_number')},
            },
        ),
    ]
