# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
import mptt.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0001_initial'),
        ('accounting', '0001_initial'),
        ('usermanagement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.location'),
        ),
        migrations.AddField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_products', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='income_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='income_products', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='product',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='batch',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='Inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.productcategory'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.batch'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.location'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.product'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='inventory_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='warehouse',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization'),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='location',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='locations', to='Inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.warehouse'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('organization', 'product', 'batch_number', 'serial_number')},
        ),
        migrations.AlterUniqueTogether(
            name='productcategory',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('organization', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='warehouse',
            unique_together={('organization', 'code')},
        ),
        migrations.AddIndex(
            model_name='stockledger',
            index=models.Index(fields=['organization', 'product', 'warehouse'], name='Inventory_s_organiz_74967d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('warehouse', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='inventoryitem',
            unique_together={('organization', 'product', 'warehouse', 'location', 'batch')},
        ),
    ]
