# Generated by Django 4.2.26 on 2025-12-02 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0002_picklist_pricelist_rma_promotionrule_pricelistitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedgerReport',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Ledger Report',
                'verbose_name_plural': 'Stock Ledger Report',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Inventory.stockledger',),
        ),
        migrations.CreateModel(
            name='StockSummary',
            fields=[
            ],
            options={
                'verbose_name': 'Stock Summary',
                'verbose_name_plural': 'Stock Summary',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Inventory.inventoryitem',),
        ),
    ]
