# Generated by Django 4.2.26 on 2025-12-03 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0158_add_coa_udf_data'),
        ('Inventory', '0003_stockledgerreport_stocksummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockledger',
            options={'ordering': ('-txn_date', '-id')},
        ),
        migrations.AlterField(
            model_name='product',
            name='expense_account',
            field=models.ForeignKey(blank=True, help_text='COGS account for inventory items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_products', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='product',
            name='inventory_account',
            field=models.ForeignKey(blank=True, help_text='Asset account for inventory items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_products', to='accounting.chartofaccount'),
        ),
    ]
