# Generated by Django 4.2.26 on 2025-12-12 07:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0169_add_auditlog_organization'),
        ('usermanagement', '0030_add_auditlog_organization'),
        ('Inventory', '0004_add_inventory_management_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='preferred_vendor_id',
        ),
        migrations.RemoveField(
            model_name='product',
            name='uom',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_count_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_issued_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_received_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_allocated',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='quantity_available',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=15),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='reorder_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.AddField(
            model_name='product',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='preferred_vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='total_cost',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=19),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
            ],
            options={
                'unique_together': {('organization', 'code')},
            },
        ),
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Inventory.unit'),
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='weight_products', to='Inventory.unit'),
        ),
        migrations.CreateModel(
            name='ProductUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_factor', models.DecimalField(decimal_places=6, help_text='Number of base units per this unit', max_digits=15)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='Inventory.product')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.unit')),
            ],
            options={
                'unique_together': {('product', 'unit')},
            },
        ),
    ]
