# Generated by Django 5.0.14 on 2025-12-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0005_remove_product_preferred_vendor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location_type',
            field=models.CharField(choices=[('storage', 'Storage'), ('staging', 'Staging'), ('qc', 'Quality Control'), ('shipping', 'Shipping'), ('receiving', 'Receiving')], default='storage', max_length=50),
        ),
    ]
