# Generated by Django 4.2.26 on 2025-12-17 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0008_transferorder_transferorderline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferorder',
            name='instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='transferorder',
            name='pick_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Inventory.picklist'),
        ),
    ]
