# Generated by Django 4.2.26 on 2025-12-18 08:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0177_merge_20251218_0016'),
        ('usermanagement', '0030_add_auditlog_organization'),
        ('Inventory', '0009_transferorder_instructions_transferorder_pick_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReorderRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reorder_level', models.DecimalField(decimal_places=4, max_digits=15)),
                ('current_stock', models.DecimalField(decimal_places=4, max_digits=15)),
                ('shortage', models.DecimalField(decimal_places=4, max_digits=15)),
                ('suggested_qty', models.DecimalField(decimal_places=4, max_digits=15)),
                ('estimated_cost', models.DecimalField(decimal_places=4, max_digits=19)),
                ('status', models.CharField(choices=[('recommended', 'Recommended'), ('ordered', 'Ordered'), ('skipped', 'Skipped')], default='recommended', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usermanagement.organization')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.product')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounting.vendor')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inventory.warehouse')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='Inventory_r_organiz_7e38cc_idx'), models.Index(fields=['product', 'warehouse'], name='Inventory_r_product_8478a6_idx')],
            },
        ),
    ]
