# Generated by Django 4.2.26 on 2025-12-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0010_reorderrecommendation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'permissions': [('scan_barcode', 'Can access barcode scanner')]},
        ),
    ]
