# Generated by Django 4.2.26 on 2025-12-20 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inventory', '0012_costing_methods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='costing_method',
            field=models.CharField(blank=True, choices=[('weighted_average', 'Weighted Average'), ('fifo', 'FIFO'), ('lifo', 'LIFO'), ('standard', 'Standard Cost')], default='weighted_average', help_text='Choose how this product is valued during inventory movements.', max_length=24),
        ),
    ]
