# Generated by Django 5.0.14 on 2025-12-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configurationentry',
            name='is_sensitive',
            field=models.BooleanField(default=False, help_text='Hide value in UI/API responses when True.'),
        ),
    ]
