# Generated by Django 4.2.26 on 2025-12-02 18:48

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inventory', '0002_picklist_pricelist_rma_promotionrule_pricelistitem_and_more'),
        ('accounting', '0158_add_coa_udf_data'),
        ('usermanagement', '0023_organization_address_organization_fiscal_year_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LandedCostDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_date', models.DateField()),
                ('basis', models.CharField(choices=[('value', 'By line value'), ('quantity', 'By quantity')], default='value', max_length=16)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('is_applied', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_documents', to='usermanagement.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('base_total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted')], default='draft', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoice', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchasing_purchase_invoices', to='usermanagement.organization')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchasing_purchase_invoices', to='accounting.vendor')),
            ],
            options={
                'ordering': ('-invoice_date', '-id'),
                'unique_together': {('organization', 'number')},
            },
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('quantity', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_account', models.ForeignKey(blank=True, help_text='Used for non-inventory items', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_expense_lines', to='accounting.chartofaccount')),
                ('input_vat_account', models.ForeignKey(blank=True, help_text='Override VAT account for this line', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_vat_lines', to='accounting.chartofaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseinvoice')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='Inventory.product')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_lines', to='Inventory.warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='LandedCostLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cost_lines', to='purchasing.landedcostdocument')),
                ('gl_account', models.ForeignKey(help_text='Source account for this cost (freight expense, customs duty, etc.)', on_delete=django.db.models.deletion.PROTECT, related_name='landed_cost_lines', to='accounting.chartofaccount')),
            ],
        ),
        migrations.AddField(
            model_name='landedcostdocument',
            name='purchase_invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_document', to='purchasing.purchaseinvoice'),
        ),
        migrations.CreateModel(
            name='LandedCostAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('factor', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=18)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='purchasing.landedcostdocument')),
                ('purchase_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_allocations', to='purchasing.purchaseinvoiceline')),
            ],
        ),
    ]
