# Generated by Django 4.2.26 on 2025-12-04 11:14

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounting', '0160_landed_cost_models'),
        ('Inventory', '0004_add_inventory_management_fields'),
        ('usermanagement', '0023_organization_address_organization_fiscal_year_start_and_more'),
        ('purchasing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('receipt_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('received', 'Goods Received'), ('inspected', 'Inspected/QC Passed'), ('posted', 'Posted to Inventory'), ('cancelled', 'Cancelled')], default='draft', max_length=16)),
                ('reference_number', models.CharField(blank=True, max_length=64)),
                ('notes', models.TextField(blank=True)),
                ('qc_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_goods_receipts', to=settings.AUTH_USER_MODEL)),
                ('journal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goods_receipt', to='accounting.journal')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goods_receipts', to='usermanagement.organization')),
            ],
            options={
                'ordering': ('-receipt_date', '-id'),
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=64)),
                ('order_date', models.DateField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('sent', 'Sent to Vendor'), ('received', 'Received'), ('closed', 'Closed')], default='draft', max_length=16)),
                ('exchange_rate', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=18)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18)),
                ('send_date', models.DateField(blank=True, null=True)),
                ('expected_receipt_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_purchase_orders', to=settings.AUTH_USER_MODEL)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounting.currency')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='purchase_orders', to='usermanagement.organization')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_orders', to='accounting.vendor')),
            ],
            options={
                'ordering': ('-order_date', '-id'),
            },
        ),
        migrations.AlterField(
            model_name='landedcostallocation',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landed_cost_allocations', to='purchasing.landedcostdocument'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.DecimalField(decimal_places=4, max_digits=18)),
                ('unit_price', models.DecimalField(decimal_places=4, max_digits=18)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('quantity_received', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('quantity_invoiced', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expense_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_expense_lines', to='accounting.chartofaccount')),
                ('inventory_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='po_inventory_lines', to='accounting.chartofaccount')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_lines', to='Inventory.product')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.purchaseorder')),
            ],
        ),
        migrations.CreateModel(
            name='GoodsReceiptLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=4, max_digits=18)),
                ('quantity_accepted', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('quantity_rejected', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=18)),
                ('serial_numbers', models.TextField(blank=True, help_text='Comma-separated if applicable')),
                ('batch_number', models.CharField(blank=True, max_length=64)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('qc_result', models.CharField(choices=[('pass', 'Passed'), ('fail', 'Failed'), ('pending', 'Pending')], default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('po_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipt_lines', to='purchasing.purchaseorderline')),
                ('receipt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='purchasing.goodsreceipt')),
            ],
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='purchase_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='receipts', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='goodsreceipt',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_receipts', to='Inventory.warehouse'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['organization', 'status', 'order_date'], name='purchasing__organiz_a52f07_idx'),
        ),
        migrations.AddIndex(
            model_name='purchaseorder',
            index=models.Index(fields=['vendor', 'status'], name='purchasing__vendor__752217_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='purchaseorder',
            unique_together={('organization', 'number')},
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['organization', 'status', 'receipt_date'], name='purchasing__organiz_5f1f34_idx'),
        ),
        migrations.AddIndex(
            model_name='goodsreceipt',
            index=models.Index(fields=['purchase_order', 'status'], name='purchasing__purchas_546b14_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='goodsreceipt',
            unique_together={('organization', 'number')},
        ),
    ]
