# Generated by Django 4.2.26 on 2025-12-21 09:44

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0190_rename_voucher_proc_journal_status_idx_voucher_pro_journal_b37e44_idx'),
        ('purchasing', '0002_goodsreceipt_purchaseorder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='agent',
            field=models.ForeignKey(blank=True, help_text='Agent handling this invoice', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_invoices', to='accounting.vendor'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='agent_area',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='invoice_date_bs',
            field=models.CharField(blank=True, help_text='Date in BS (YYYY-MM-DD)', max_length=10),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='narration',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='payment_mode',
            field=models.CharField(choices=[('cash', 'Cash'), ('credit', 'Credit'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer')], default='credit', max_length=32),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='Header level purchase account (optional default)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices_header', to='accounting.chartofaccount'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='purchasing.purchaseorder'),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='rounding_adjustment',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Reference/Party Invoice Number', max_length=64),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='taxable_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AddField(
            model_name='purchaseinvoice',
            name='terms_and_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='PurchaseInvoiceAdditionalCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=18)),
                ('is_taxable', models.BooleanField(default=False, help_text='Does VAT apply to this charge?')),
                ('gl_account', models.ForeignKey(help_text='GL Account to expense/income this charge', on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_charges', to='purchasing.purchaseinvoice')),
            ],
        ),
    ]
