# Generated by Django 4.2.26 on 2025-12-21 10:26

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0192_currency_isdefault_agent'),
        ('purchasing', '0003_purchaseinvoice_agent_purchaseinvoice_agent_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseinvoice',
            name='additional_charges_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_invoices', to='accounting.agent'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='invoice_date_bs',
            field=models.CharField(blank=True, help_text='Date in BS (populated via AD-BS converter)', max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='purchase_account',
            field=models.ForeignKey(blank=True, help_text='Header level default purchase account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_invoices_header', to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoice',
            name='supplier_invoice_number',
            field=models.CharField(blank=True, help_text='Party Invoice Number', max_length=64),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceadditionalcharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='Positive for charges, negative for discounts', max_digits=18),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceadditionalcharge',
            name='gl_account',
            field=models.ForeignKey(help_text='GL Account to post this charge', on_delete=django.db.models.deletion.PROTECT, to='accounting.chartofaccount'),
        ),
        migrations.AlterField(
            model_name='purchaseinvoiceadditionalcharge',
            name='is_taxable',
            field=models.BooleanField(default=False, help_text='Apply VAT to this charge?'),
        ),
        migrations.AlterModelTable(
            name='purchaseinvoiceadditionalcharge',
            table='purchase_invoice_additional_charge',
        ),
    ]
