# Generated by Django 4.2.26 on 2025-12-21 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('purchasing', '0004_purchaseinvoice_additional_charges_total_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landedcostdocument',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='landedcostdocument',
            name='purchase_invoice',
        ),
        migrations.RemoveField(
            model_name='landedcostline',
            name='document',
        ),
        migrations.RemoveField(
            model_name='landedcostline',
            name='gl_account',
        ),
        migrations.AlterUniqueTogether(
            name='purchaseinvoice',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='agent',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='journal',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_account',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='purchase_order',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoice',
            name='supplier',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceadditionalcharge',
            name='gl_account',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceadditionalcharge',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='expense_account',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='input_vat_account',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='invoice',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='product',
        ),
        migrations.RemoveField(
            model_name='purchaseinvoiceline',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='LandedCostAllocation',
        ),
        migrations.DeleteModel(
            name='LandedCostDocument',
        ),
        migrations.DeleteModel(
            name='LandedCostLine',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoice',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceAdditionalCharge',
        ),
        migrations.DeleteModel(
            name='PurchaseInvoiceLine',
        ),
    ]
