# Generated by Django 4.2.26 on 2025-12-09 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Inventory', '0004_add_inventory_management_fields'),
        ('usermanagement', '0029_permission_usermanagem_codenam_fe4df3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('cart_id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pos_cart',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_customer_name', models.CharField(default='Walk-in Customer', max_length=255)),
                ('enable_barcode_scanner', models.BooleanField(default=True)),
                ('enable_camera_scanner', models.BooleanField(default=False)),
                ('show_item_images', models.BooleanField(default=True)),
                ('receipt_printer_name', models.CharField(blank=True, max_length=255)),
                ('cash_drawer_enabled', models.BooleanField(default=False)),
                ('auto_print_receipt', models.BooleanField(default=True)),
                ('default_payment_method', models.CharField(default='cash', max_length=50)),
                ('tax_inclusive_pricing', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
            ],
            options={
                'db_table': 'pos_settings',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('cart_item_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=200)),
                ('product_code', models.CharField(max_length=50)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('quantity', models.DecimalField(decimal_places=4, default=1, max_digits=19)),
                ('unit_price', models.DecimalField(decimal_places=6, default=0, max_digits=19)),
                ('discount_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('line_total', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('tax_amount', models.DecimalField(decimal_places=4, default=0, max_digits=19)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='pos.cart')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Inventory.product')),
            ],
            options={
                'db_table': 'pos_cart_item',
                'ordering': ['created_at'],
            },
        ),
    ]
