import os
import re
import shutil

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
APP_DIR = os.path.join(BASE_DIR, "accounting")

MODULES = ["views", "forms", "services", "repositories"]
ENTITY_HINTS = [
    "ChartOfAccount", "VoucherModeConfig", "Journal", "Tax", "Voucher", "Entry", "Line"
]

def ensure_dir(path):
    if not os.path.exists(path):
        os.makedirs(path)

def move_classes_to_files(module):
    module_dir = os.path.join(APP_DIR, module)
    ensure_dir(module_dir)
    monolithic_file = os.path.join(APP_DIR, f"{module}.py")
    if not os.path.exists(monolithic_file):
        return

    with open(monolithic_file, "r", encoding="utf-8") as f:
        content = f.read()

    # Find all class definitions for known entities
    for entity in ENTITY_HINTS:
        pattern = rf"(class {entity}\w*\(.*?\):[\s\S]+?)(?=\nclass |\Z)"
        matches = re.findall(pattern, content)
        for match in matches:
            # Determine filename
            class_name = re.findall(r"class (\w+)\(", match)[0]
            file_name = f"{entity.lower()}_{module[:-1] if module.endswith('s') else module}.py"
            file_path = os.path.join(module_dir, file_name)
            # Write class to its own file (append if multiple per entity)
            with open(file_path, "a", encoding="utf-8") as ef:
                ef.write(f"{match}\n\n")
            print(f"Moved {class_name} to {file_path}")

    # Remove all moved classes from monolithic file
    for entity in ENTITY_HINTS:
        content = re.sub(rf"(class {entity}\w*\(.*?\):[\s\S]+?)(?=\nclass |\Z)", "", content)

    # Save cleaned monolithic file
    with open(monolithic_file, "w", encoding="utf-8") as f:
        f.write(content.strip())

def rewrite_init(module):
    module_dir = os.path.join(APP_DIR, module)
    init_file = os.path.join(module_dir, "__init__.py")
    lines = []
    for fname in sorted(os.listdir(module_dir)):
        if fname.endswith(".py") and fname != "__init__.py":
            modname = fname[:-3]
            with open(os.path.join(module_dir, fname), "r", encoding="utf-8") as f:
                classes = re.findall(r"class (\w+)\(", f.read())
                for cls in classes:
                    lines.append(f"from .{modname} import {cls}")
    with open(init_file, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by modularize_accounting.py\n" + "\n".join(lines) + "\n")
    print(f"Rewrote {init_file}")

def main():
    print("Starting modularization...")
    for module in MODULES:
        move_classes_to_files(module)
        rewrite_init(module)
    print("Modularization complete. Please review changes and run your tests.")

if __name__ == "__main__":
    main()