# Generated by Django 4.2.26 on 2025-12-24 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClusterTag',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('name_en', models.CharField(max_length=128)),
                ('name_np', models.CharField(max_length=128)),
                ('scope_type', models.CharField(choices=[('COMPANY', 'Company'), ('BRANCH', 'Branch'), ('DISTRICT', 'District'), ('LOCAL_LEVEL', 'Local level')], max_length=16)),
                ('is_active', models.BooleanField(default=True)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='LocationNode',
            fields=[
                ('id', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('COUNTRY', 'Country'), ('PROVINCE', 'Province'), ('DISTRICT', 'District'), ('LOCAL_LEVEL', 'Local level (Municipality/Gaupalika)'), ('WARD', 'Ward'), ('AREA', 'Area/Locality')], max_length=16)),
                ('name_en', models.CharField(max_length=128)),
                ('name_np', models.CharField(max_length=128)),
                ('code', models.CharField(blank=True, default='', max_length=32)),
                ('is_active', models.BooleanField(default=True)),
                ('aliases_en', models.JSONField(blank=True, default=list)),
                ('aliases_np', models.JSONField(blank=True, default=list)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='locations.locationnode')),
            ],
        ),
        migrations.CreateModel(
            name='ClusterTagMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.clustertag')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='locations.locationnode')),
            ],
        ),
        migrations.AddField(
            model_name='clustertag',
            name='members',
            field=models.ManyToManyField(blank=True, related_name='cluster_tags', through='locations.ClusterTagMembership', to='locations.locationnode'),
        ),
        migrations.AddField(
            model_name='clustertag',
            name='scope_location',
            field=models.ForeignKey(blank=True, help_text='For LOCAL_LEVEL/DISTRICT scope. Leave null for COMPANY/BRANCH scope.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='scoped_cluster_tags', to='locations.locationnode'),
        ),
        migrations.CreateModel(
            name='AddressRef',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line1', models.CharField(blank=True, default='', max_length=128)),
                ('address_line2', models.CharField(blank=True, default='', max_length=128)),
                ('landmark', models.CharField(blank=True, default='', max_length=128)),
                ('postal_code', models.CharField(blank=True, default='', max_length=16)),
                ('area', models.ForeignKey(blank=True, limit_choices_to={'type': 'AREA'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_areas', to='locations.locationnode')),
                ('cluster_tags', models.ManyToManyField(blank=True, related_name='addresses', to='locations.clustertag')),
                ('local_level', models.ForeignKey(limit_choices_to={'type': 'LOCAL_LEVEL'}, on_delete=django.db.models.deletion.PROTECT, related_name='address_local_levels', to='locations.locationnode')),
                ('ward', models.ForeignKey(blank=True, limit_choices_to={'type': 'WARD'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='address_wards', to='locations.locationnode')),
            ],
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['type', 'is_active'], name='locations_l_type_211ef3_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['parent', 'type', 'is_active'], name='locations_l_parent__bbefc0_idx'),
        ),
        migrations.AddIndex(
            model_name='locationnode',
            index=models.Index(fields=['name_en'], name='locations_l_name_en_45dd5a_idx'),
        ),
        migrations.AddIndex(
            model_name='clustertagmembership',
            index=models.Index(fields=['cluster', 'node'], name='locations_c_cluster_330a55_idx'),
        ),
        migrations.AddIndex(
            model_name='clustertagmembership',
            index=models.Index(fields=['node'], name='locations_c_node_id_cfc2e0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='clustertagmembership',
            unique_together={('cluster', 'node')},
        ),
        migrations.AddIndex(
            model_name='clustertag',
            index=models.Index(fields=['scope_type', 'is_active'], name='locations_c_scope_t_f80edc_idx'),
        ),
        migrations.AddIndex(
            model_name='clustertag',
            index=models.Index(fields=['scope_location', 'is_active'], name='locations_c_scope_l_7efb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='addressref',
            index=models.Index(fields=['local_level'], name='locations_a_local_l_4b87bb_idx'),
        ),
    ]
