# Generated by Django 5.2.1 on 2025-05-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0004_loginlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loginlog',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='updated_by',
        ),
        migrations.AlterField(
            model_name='loginlog',
            name='login_method',
            field=models.CharField(choices=[('email', 'Email'), ('google', 'Google'), ('facebook', 'Facebook')], max_length=50),
        ),
    ]
