# Generated by Django 5.2.1 on 2025-05-18 15:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0007_alter_loginlog_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='logout_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='loginlog',
            name='session_time',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
