# Generated by Django 5.2.1 on 2025-05-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0008_loginlog_logout_time_loginlog_session_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginlog',
            name='session_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
