# Generated by Django 5.2.1 on 2025-05-18 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0010_alter_loginlog_created_by_alter_loginlog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginlog',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
