# Generated by Django 5.0.14 on 2025-05-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0011_loginlog_failure_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='tenant',
        ),
    ]
