# Generated by Django 5.0.14 on 2025-06-06 18:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0012_remove_organization_tenant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('codename', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('action', models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('special', 'Special')], max_length=20)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.entity')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.module')),
            ],
            options={
                'unique_together': {('codename', 'module', 'entity')},
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('permissions', models.ManyToManyField(to='usermanagement.permission')),
            ],
            options={
                'unique_together': {('name', 'organization')},
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usermanagement.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'role', 'organization')},
            },
        ),
    ]
