# Generated by Django 5.0.14 on 2025-06-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0015_alter_entity_options_alter_module_options_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['user', 'login_datetime'], name='usermanagem_user_id_15a248_idx'),
        ),
        migrations.AddIndex(
            model_name='loginlog',
            index=models.Index(fields=['session_id'], name='usermanagem_session_45d5c2_idx'),
        ),
    ]
