# Generated by Django 5.0.14 on 2025-06-10 15:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0016_loginlog_usermanagem_user_id_15a248_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppViewLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_path', models.CharField(max_length=255)),
                ('view_datetime', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_id', models.CharField(blank=True, max_length=64, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('method', models.CharField(blank=True, max_length=10, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_app_logs', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-view_datetime'],
                'indexes': [models.Index(fields=['user', 'view_datetime'], name='usermanagem_user_id_435172_idx'), models.Index(fields=['view_path'], name='usermanagem_view_pa_d83959_idx'), models.Index(fields=['session_id'], name='usermanagem_session_2b68f6_idx')],
            },
        ),
    ]
