# Generated by Django 5.0.14 on 2025-06-10 16:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0017_appviewlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('view', 'View'), ('create', 'Create'), ('edit', 'Edit'), ('delete', 'Delete'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={},
        ),
        migrations.RenameField(
            model_name='module',
            old_name='display_order',
            new_name='order',
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='entity',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entity',
            name='url_pattern',
            field=models.CharField(default=django.utils.timezone.now, help_text="URL pattern for this entity (e.g., 'accounting/currencies/')", max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='module',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='module',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_modules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(help_text="Icon class name (e.g., 'fas fa-users')", max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['code'], name='usermanagem_code_fb9b04_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['module'], name='usermanagem_module__72791a_idx'),
        ),
        migrations.AddIndex(
            model_name='entity',
            index=models.Index(fields=['is_active'], name='usermanagem_is_acti_acd1bf_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['code'], name='usermanagem_code_2a9cdc_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['order'], name='usermanagem_order_be38fa_idx'),
        ),
        migrations.AddIndex(
            model_name='module',
            index=models.Index(fields=['is_active'], name='usermanagem_is_acti_faf166_idx'),
        ),
        migrations.AddField(
            model_name='entitypermission',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entitypermission',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_permissions', to='usermanagement.entity'),
        ),
        migrations.AddField(
            model_name='entitypermission',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entity_permissions', to='usermanagement.role'),
        ),
        migrations.AddField(
            model_name='entitypermission',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='entity',
            name='display_order',
        ),
        migrations.AddIndex(
            model_name='entitypermission',
            index=models.Index(fields=['role', 'entity', 'action'], name='usermanagem_role_id_c9b2d0_idx'),
        ),
        migrations.AddIndex(
            model_name='entitypermission',
            index=models.Index(fields=['is_active'], name='usermanagem_is_acti_b5cda3_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='entitypermission',
            unique_together={('role', 'entity', 'action')},
        ),
    ]
