# Generated by Django 5.0.14 on 2025-06-11 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0018_entitypermission_alter_entity_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appviewlog',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='appviewlog',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='entitypermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='entitypermission',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entitypermission',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='entitypermission',
            name='role',
        ),
        migrations.RemoveField(
            model_name='entitypermission',
            name='updated_by',
        ),
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['module', 'display_order', 'name']},
        ),
        migrations.AlterModelOptions(
            name='module',
            options={'ordering': ['display_order', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='usermanagem_code_fb9b04_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='usermanagem_module__72791a_idx',
        ),
        migrations.RemoveIndex(
            model_name='entity',
            name='usermanagem_is_acti_acd1bf_idx',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='usermanagem_code_2a9cdc_idx',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='usermanagem_order_be38fa_idx',
        ),
        migrations.RemoveIndex(
            model_name='module',
            name='usermanagem_is_acti_faf166_idx',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='order',
            new_name='display_order',
        ),
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together={('module', 'code')},
        ),
        migrations.RemoveField(
            model_name='module',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='module',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='entity',
            name='display_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='entity',
            name='code',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='entity',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='module',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AppViewLog',
        ),
        migrations.DeleteModel(
            name='EntityPermission',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='url_pattern',
        ),
    ]
