# Generated by Django 5.0.14 on 2025-08-14 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0020_userpermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('approve', 'Approve'), ('reject', 'Reject'), ('submit', 'Submit'), ('modify', 'Modify'), ('special', 'Special')], max_length=20),
        ),
    ]
