# Generated by Django 5.0.14 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0021_alter_permission_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='action',
            field=models.CharField(choices=[('view', 'View'), ('add', 'Add'), ('change', 'Change'), ('delete', 'Delete'), ('submit', 'Submit'), ('approve', 'Approve'), ('reject', 'Reject'), ('post', 'Post'), ('reverse', 'Reverse'), ('modify', 'Modify'), ('special', 'Special'), ('submit_journal', 'Submit Journal'), ('approve_journal', 'Approve Journal'), ('reject_journal', 'Reject Journal'), ('post_journal', 'Post Journal'), ('reverse_journal', 'Reverse Journal'), ('close_period', 'Close Period'), ('reopen_period', 'Reopen Period'), ('close_fiscalyear', 'Close Fiscal Year'), ('reopen_fiscalyear', 'Reopen Fiscal Year')], max_length=50),
        ),
    ]
