# Generated by Django 4.2.26 on 2025-11-25 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_tenantbrandingconfig'),
        ('usermanagement', '0022_alter_permission_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='organization',
            name='fiscal_year_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='tenancy.tenant'),
        ),
        migrations.AddField(
            model_name='organization',
            name='vertical_type',
            field=models.CharField(choices=[('retailer', 'Retailer'), ('depot', 'Depot'), ('logistics', 'Logistics')], default='retailer', help_text='Operational vertical for feature toggles.', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('superadmin', 'Super Admin'), ('admin', 'Admin'), ('manager', 'Manager'), ('accountant', 'Accountant'), ('data_entry', 'Data Entry'), ('user', 'User')], default='user', max_length=50),
        ),
        migrations.CreateModel(
            name='CompanyConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enable_noc_purchases', models.BooleanField(default=False)),
                ('enable_dealer_management', models.BooleanField(default=True)),
                ('enable_logistics', models.BooleanField(default=False)),
                ('enable_advanced_inventory', models.BooleanField(default=False)),
                ('enforce_credit_limit', models.BooleanField(default=True)),
                ('credit_enforcement_mode', models.CharField(choices=[('block', 'Block'), ('warn', 'Warn')], default='block', help_text='How to handle dealer credit limit breaches.', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='usermanagement.organization')),
            ],
            options={
                'db_table': 'company_config',
            },
        ),
    ]
