# Generated by Django 5.0.14 on 2025-12-08 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0161_currency_isdefault_currency_unique_default_currency'),
        ('usermanagement', '0025_companyconfig_calendar_date_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='base_currency_code',
            field=models.ForeignKey(blank=True, db_column='base_currency_code', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to='accounting.currency'),
        ),
    ]
