# Generated by Django 4.2.26 on 2025-12-09 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0028_companyconfig_invoice_template'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['codename'], name='usermanagem_codenam_fe4df3_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['module', 'entity'], name='usermanagem_module__e683b1_idx'),
        ),
        migrations.AddIndex(
            model_name='permission',
            index=models.Index(fields=['is_active'], name='usermanagem_is_acti_735439_idx'),
        ),
        migrations.AddIndex(
            model_name='userpermission',
            index=models.Index(fields=['user', 'organization'], name='usermanagem_user_id_45767e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'organization', 'is_active'], name='usermanagem_user_id_696339_idx'),
        ),
    ]
