# Generated by Django 4.2.26 on 2025-12-10 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usermanagement', '0029_permission_usermanagem_codenam_fe4df3_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('login_failed_invalid_creds', 'Failed - Invalid Credentials'), ('login_failed_account_locked', 'Failed - Account Locked'), ('login_failed_mfa', 'Failed - MFA Required/Failed'), ('login_failed_disabled_account', 'Failed - Account Disabled'), ('logout', 'Logout'), ('session_timeout', 'Session Timeout'), ('password_changed', 'Password Changed'), ('mfa_enabled', 'MFA Enabled'), ('mfa_disabled', 'MFA Disabled'), ('account_locked', 'Account Locked'), ('account_unlocked', 'Account Unlocked')], db_index=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of login attempt')),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string')),
                ('session_id', models.CharField(blank=True, max_length=128, null=True)),
                ('auth_method', models.CharField(choices=[('email', 'Email/Password'), ('google', 'Google OAuth'), ('facebook', 'Facebook OAuth'), ('saml', 'SAML'), ('api_token', 'API Token')], default='email', max_length=50)),
                ('mfa_method', models.CharField(blank=True, choices=[('totp', 'TOTP App'), ('sms', 'SMS'), ('email', 'Email'), ('backup_code', 'Backup Code')], max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('login_duration', models.DurationField(blank=True, help_text='How long session lasted', null=True)),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failed login', max_length=255)),
                ('country_code', models.CharField(blank=True, help_text='Two-letter country code', max_length=2)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('is_suspicious', models.BooleanField(default=False, help_text='Flagged by anomaly detection')),
                ('risk_score', models.SmallIntegerField(default=0, help_text='0-100 risk score')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usermanagement.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Login Event Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='usermanagem_user_id_352d8f_idx'), models.Index(fields=['organization', 'timestamp'], name='usermanagem_organiz_546473_idx'), models.Index(fields=['timestamp'], name='usermanagem_timesta_cabb5e_idx'), models.Index(fields=['event_type'], name='usermanagem_event_t_a3e718_idx'), models.Index(fields=['ip_address'], name='usermanagem_ip_addr_9f3ef0_idx'), models.Index(fields=['is_suspicious'], name='usermanagem_is_susp_d96eca_idx')],
            },
        ),
    ]
