# Generated by Django 5.0.14 on 2025-07-03 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0035_alter_fiscalyear_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VoucherSchema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('voucher_mode_config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='accounting.vouchermodeconfig')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('voucher_mode_config', 'version')},
            },
        ),
    ]
