# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('forms_designer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='voucherschema',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucherschema',
            name='voucher_mode_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schemas', to='accounting.vouchermodeconfig'),
        ),
        migrations.AlterUniqueTogether(
            name='voucherschema',
            unique_together={('voucher_mode_config', 'version')},
        ),
    ]
