# Generated by Django 5.2.5 on 2025-08-20 18:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # Keep the swappable user dependency, but avoid duplicating accounting/forms_designer FKs if
        # those apps already ran their own initial migrations in the target database. The
        # database-level operations below handle idempotency.
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forms_designer', '0001_initial'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_schema = current_schema()
                                  AND table_name = 'forms_designer_voucherschema'
                                  AND column_name = 'created_by_id'
                            ) THEN
                                ALTER TABLE "forms_designer_voucherschema"
                                ADD COLUMN created_by_id bigint
                                REFERENCES "auth_user" (id)
                                DEFERRABLE INITIALLY DEFERRED;
                            END IF;
                        END;
                        $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE "forms_designer_voucherschema"
                        DROP COLUMN IF EXISTS created_by_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='voucherschema',
                    name='created_by',
                    field=models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunSQL(
                    sql="""
                        DO $$
                        BEGIN
                            IF NOT EXISTS (
                                SELECT 1 FROM information_schema.columns
                                WHERE table_schema = current_schema()
                                  AND table_name = 'forms_designer_voucherschema'
                                  AND column_name = 'voucher_mode_config_id'
                            ) THEN
                                ALTER TABLE "forms_designer_voucherschema"
                                ADD COLUMN voucher_mode_config_id bigint
                                REFERENCES "accounting_vouchermodeconfig" (id)
                                DEFERRABLE INITIALLY DEFERRED;
                            END IF;
                        END;
                        $$;
                    """,
                    reverse_sql="""
                        ALTER TABLE "forms_designer_voucherschema"
                        DROP COLUMN IF EXISTS voucher_mode_config_id;
                    """,
                ),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='voucherschema',
                    name='voucher_mode_config',
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='schemas',
                        to='accounting.vouchermodeconfig',
                    ),
                ),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='voucherschema',
            unique_together={('voucher_mode_config', 'version')},
        ),
    ]
