# Generated by Django 5.0.14 on 2025-11-03 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms_designer', '0003_enhanced_schema_features'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='voucherschema',
            new_name='forms_desig_voucher_1094c8_idx',
            old_name='forms_desig_voucher_idx1',
        ),
        migrations.RenameIndex(
            model_name='voucherschema',
            new_name='forms_desig_voucher_c733b6_idx',
            old_name='forms_desig_voucher_idx2',
        ),
        migrations.AlterField(
            model_name='voucherschema',
            name='schema',
            field=models.JSONField(help_text='Complete form schema with fields, layout, and validation rules'),
        ),
    ]
